#!/usr/bin/env python3
"""
extract_xray.py  --  AJ Bell ISA Portfolio X-Ray PDF parser
Version: 1.0  |  2026-05-31

Reads the latest AJ Bell ISA Portfolio X-Ray PDF from the ISA folder and produces
a clean xray_data_mmm_yyyy.json. Called by monthly_isa_prerun.py.

Usage (standalone):
    python3 extract_xray.py [--pdf /path/to/file.pdf] [--out /path/to/output.json]

Output: xray_data_mmm_yyyy.json with:
  - Asset allocation (stocks, bonds, cash, other)
  - Geographic/country exposure (vs benchmark)
  - World region breakdown (vs benchmark)
  - Stock sector weights (vs benchmark)
  - Investment style box
  - Trailing performance (3m, 6m, 1yr, 3yr, 5yr, YTD)
  - Per-fund holdings table (name, Morningstar rating, 1yr/3yr/5yr returns, weight %, TER)

PDF format: Morningstar Portfolio X-Ray as generated by AJ Bell.
Parsing uses a combination of pdfplumber text extraction and regex.
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime

import pdfplumber


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
ISA_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# Morningstar star rating — AJ Bell PDF uses "Q" for stars
MS_RATING_MAP = {"QQQQQ": 5, "QQQQ": 4, "QQQ": 3, "QQ": 2, "Q": 1}

# Known sector codes in X-Ray PDF
SECTOR_MAP = {
    "Basic Materials":       "basic_materials",
    "Communication Services":"communication_services",
    "Consumer Cyclical":     "consumer_cyclical",
    "Consumer Defensive":    "consumer_defensive",
    "Energy":                "energy",
    "Financial Services":    "financial_services",
    "Healthcare":            "healthcare",
    "Industrials":           "industrials",
    "Real Estate":           "real_estate",
    "Technology":            "technology",
    "Utilities":             "utilities",
}


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------
def find_latest_xray(folder: str) -> str:
    """Find latest AJ Bell ISA Portfolio X-Ray PDF (not 'End of Tax Year')."""
    pattern = os.path.join(folder, "AJ Bell ISA Portfolio X-Ray *.pdf")
    candidates = [
        f for f in glob.glob(pattern)
        if "end of tax year" not in os.path.basename(f).lower()
    ]
    if not candidates:
        raise FileNotFoundError(
            f"No AJ Bell ISA Portfolio X-Ray PDF found in: {folder}\n"
            f"Expected filename: 'AJ Bell ISA Portfolio X-Ray DD-Mmm-YY.pdf'"
        )

    def _parse_date(path):
        name = os.path.basename(path)
        m = re.search(r"(\d{2}-\w{3}-\d{2,4})\.pdf$", name, re.IGNORECASE)
        if m:
            for fmt in ("%d-%b-%y", "%d-%b-%Y"):
                try:
                    return datetime.strptime(m.group(1), fmt)
                except ValueError:
                    pass
        return datetime.min

    return max(candidates, key=_parse_date)


# ---------------------------------------------------------------------------
# Text extraction helpers
# ---------------------------------------------------------------------------
def extract_all_text(pdf_path: str) -> str:
    """Extract all text from PDF, one page at a time, joined with newlines."""
    pages = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            t = page.extract_text() or ""
            pages.append(t)
    return "\n\n".join(pages)


def safe_float(s: str) -> float | None:
    """Convert string to float, return None on failure."""
    if s is None:
        return None
    s = str(s).strip().replace(",", "").replace("%", "")
    if s in ("", "-", "—", "N/A", "n/a"):
        return None
    try:
        return float(s)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Parser sections
# ---------------------------------------------------------------------------
def parse_report_date(text: str) -> str:
    m = re.search(r"Report as of\s+(\d+\s+\w+\s+\d{4})", text)
    if m:
        try:
            dt = datetime.strptime(m.group(1), "%d %B %Y")
            return dt.strftime("%d-%b-%Y")
        except ValueError:
            return m.group(1)
    m2 = re.search(r"Date\s*:\s*(\w+\s+\d+\s+\d{4})", text)
    if m2:
        try:
            dt = datetime.strptime(m2.group(1), "%B %d %Y")
            return dt.strftime("%d-%b-%Y")
        except ValueError:
            return m2.group(1)
    return "unknown"


def parse_asset_allocation(text: str) -> dict:
    """Extract asset allocation percentages from X-Ray page 2 text."""
    result = {}
    # Pattern: "Stocks 90.31 0.05 90.26"
    for asset in ["Stocks", "Bonds", "Cash", "Other", "Not classified"]:
        m = re.search(
            rf"{re.escape(asset)}\s+([\d.]+)\s+([\d.]+)\s+([\-\d.]+)", text
        )
        if m:
            key = asset.lower().replace(" ", "_")
            result[key] = {
                "long_pct":  safe_float(m.group(1)),
                "short_pct": safe_float(m.group(2)),
                "net_pct":   safe_float(m.group(3)),
            }
    return result


# Fix Pack A10 (P2): STATIC country whitelist — the old catch-all [A-Z][a-z]+ arm ingested
# header/label rows as data ("June" 2026.0, "Benchmark" rows). Whitelist + 0-100 pct-range
# validation; rejected rows land in PARSE_WARNINGS (surfaced via _meta.parse_warnings and the
# pre-run schema assert). "Other"/"Others" is a legitimate residual row and is included.
COUNTRY_WHITELIST = frozenset([
    "United States", "United Kingdom", "Japan", "China", "France", "Taiwan",
    "Republic of Korea", "South Korea", "Spain", "Italy", "Germany", "Canada",
    "Australia", "Netherlands", "Switzerland", "Sweden", "Denmark", "Norway",
    "Finland", "India", "Brazil", "Hong Kong", "Singapore", "Mexico", "Belgium",
    "Austria", "Ireland", "Portugal", "Israel", "New Zealand", "South Africa",
    "Indonesia", "Malaysia", "Thailand", "Philippines", "Vietnam", "Poland",
    "Turkey", "Greece", "Chile", "Colombia", "Peru", "Argentina", "Saudi Arabia",
    "United Arab Emirates", "Qatar", "Kuwait", "Egypt", "Luxembourg", "Iceland",
    "Other", "Others",
])

PARSE_WARNINGS: list = []   # A10 — reset per extract run; copied into _meta.parse_warnings


def _valid_pct(v):
    return v is None or (isinstance(v, (int, float)) and 0.0 <= v <= 100.0)


def parse_country_exposure(text: str) -> list:
    """
    Extract country exposure table. Returns list of
    {country, equity_pct, benchmark_pct}.
    A10: whitelist countries; reject pct outside 0-100; rejected rows -> PARSE_WARNINGS.
    """
    countries = []
    # Lines like: "United States 40.03 65.85" (two side-by-side columns in PDF text)
    pattern = re.compile(
        r"([A-Z][A-Za-z]+(?:\s[A-Za-z][A-Za-z]+){0,3})"
        r"\s+([\d.]+)\s+([\d.]+)"
    )
    for m in pattern.finditer(text):
        name = m.group(1).strip()
        eq, bench = safe_float(m.group(2)), safe_float(m.group(3))
        if name not in COUNTRY_WHITELIST:
            # header/label/date rows are EXPECTED matches of the loose pattern — only warn on
            # rows that look plausibly geographic (both pcts in range) so the warning list
            # stays signal, not noise
            if _valid_pct(eq) and _valid_pct(bench) and eq is not None:
                PARSE_WARNINGS.append(f"country row rejected (not whitelisted): {name!r} {eq}/{bench}")
            continue
        if not (_valid_pct(eq) and _valid_pct(bench)):
            PARSE_WARNINGS.append(f"country row rejected (pct out of 0-100): {name!r} {eq}/{bench}")
            continue
        countries.append({
            "country":       name,
            "equity_pct":    eq,
            "benchmark_pct": bench,
        })
    # Deduplicate (PDF may repeat entries)
    seen = set()
    unique = []
    for c in countries:
        k = c["country"]
        if k not in seen:
            seen.add(k)
            unique.append(c)
    return unique


def parse_world_regions(text: str) -> dict:
    """Extract world region breakdown {region: {equity_pct, benchmark_pct}}."""
    regions = {}
    # Pattern: "Greater Europe 34.73 19.34"
    region_names = [
        "Greater Europe", "Americas", "Greater Asia",
        "United Kingdom", "Western Europe",
        "United States", "Canada",
        "Japan", "Australasia",
        "Emerging 4 Tigers", "Emerging Asia",
        "Emerging Europe", "Middle East / Africa",
        "Central & Latin America",
    ]
    for rn in region_names:
        m = re.search(
            rf"{re.escape(rn)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if m:
            key = rn.lower().replace(" ", "_").replace("/", "_").replace("&", "and")
            regions[key] = {
                "name":          rn,
                "equity_pct":    safe_float(m.group(1)),
                "benchmark_pct": safe_float(m.group(2)),
            }
    return regions


def parse_sector_weights(text: str) -> dict:
    """
    Extract stock sector weights vs benchmark.
    Returns {sector_key: {name, portfolio_pct, benchmark_pct}}.
    """
    sectors = {}
    # Pattern lines: "sConsumer 5.59 5.16" or "yFinancial 17.42 16.54"
    # The PDF prefixes each sector with a single letter icon — strip it.
    for sector_name, key in SECTOR_MAP.items():
        # Match the sector name (possibly with leading letter/icon) followed by two numbers
        m = re.search(
            rf".{{0,3}}{re.escape(sector_name)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if not m:
            # Try abbreviated name (first word only for communication services etc.)
            short = sector_name.split()[0]
            m = re.search(rf".{{0,3}}{re.escape(short)}\w*\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            sectors[key] = {
                "name":          sector_name,
                "portfolio_pct": safe_float(m.group(1)),
                "benchmark_pct": safe_float(m.group(2)),
                "vs_benchmark":  round(
                    (safe_float(m.group(1)) or 0) - (safe_float(m.group(2)) or 0), 2
                ),
            }
    return sectors


def parse_trailing_returns(text: str) -> dict:
    """
    Extract trailing returns table.
    Returns {period: {portfolio_pct, benchmark_pct, relative_pct}}.
    """
    returns = {}
    periods = {
        "3 Months":           "3m",
        "6 Months":           "6m",
        "1 Year":             "1yr",
        "3 Years Annualised": "3yr_ann",
        "5 Years Annualised": "5yr_ann",
        "YTD":                "ytd",
    }
    for label, key in periods.items():
        m = re.search(
            rf"{re.escape(label)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if m:
            port  = safe_float(m.group(1))
            bench = safe_float(m.group(2))
            rel   = round((port or 0) - (bench or 0), 2) if port is not None and bench is not None else None
            returns[key] = {
                "period":        label,
                "portfolio_pct": port,
                "benchmark_pct": bench,
                "relative_pct":  rel,
            }
    return returns


def parse_fund_holdings(text: str) -> list:
    """
    Extract Portfolio Holdings table (page 4 of PDF).
    Returns list of fund dicts.
    """
    funds = []

    # Find the holdings section
    holdings_start = text.find("Portfolio Holdings\nName Type Holding")
    if holdings_start == -1:
        holdings_start = text.find("Portfolio Holdings")
    if holdings_start == -1:
        return funds

    section = text[holdings_start:]

    # Each fund line (approximate):
    # "FUND NAME Type Date MS_RATING 1yr 3yr 5yr weight% TER OC"
    # Use a flexible pattern
    fund_pattern = re.compile(
        r"([A-Z][A-Z &\-\.\'()]+)\s+"           # Fund name (caps)
        r"(?:Fund|Mutual Fund|ETF|Cash)\s*"      # Type
        r"(?:-|ETF)?\s*"
        r"(?:\d+ \w+ \d{4})?\s*"                # Optional holding date
        r"(Q{1,5}|-)\s*"                         # MS Rating (Q's or dash)
        r"([\d.]+|-)\s+"                          # 1yr
        r"([\d.]+|-)?\s*"                        # 3yr
        r"([\d.]+|-)?\s*"                        # 5yr
        r"([\d.]+)\s*"                           # weight %
        r"(-)\s*"                                # TER (always - in AJ Bell)
        r"([\d.]+|-)",                           # Ongoing cost
        re.IGNORECASE
    )

    for m in fund_pattern.finditer(section):
        name = m.group(1).strip()
        if len(name) < 5 or name.upper().startswith("NAME"):
            continue
        ms_str = m.group(2).strip()
        ms_rating = MS_RATING_MAP.get(ms_str) if ms_str != "-" else None

        fund_rec = {
            "name":         name,
            "ms_rating":    ms_rating,
            "return_1yr":   safe_float(m.group(3)),
            "return_3yr":   safe_float(m.group(4)),
            "return_5yr":   safe_float(m.group(5)),
            "weight_pct":   safe_float(m.group(6)),
            "ongoing_cost": safe_float(m.group(8)),
        }
        funds.append(fund_rec)

    # Deduplicate by name
    seen = set()
    unique = []
    for f in funds:
        k = f["name"][:20]
        if k not in seen:
            seen.add(k)
            unique.append(f)

    return unique


def parse_investment_style(text: str) -> dict:
    """Extract style box summary metrics."""
    style = {}
    for metric, key in [
        ("Price/Book Ratio",    "price_book"),
        ("Price/Earnings",      "price_earnings"),
        ("Price/Cashflow",      "price_cashflow"),
    ]:
        m = re.search(rf"{re.escape(metric)}\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            style[key] = {
                "portfolio":  safe_float(m.group(1)),
                "benchmark":  safe_float(m.group(2)),
            }
    return style


def parse_rstat(text: str) -> dict:
    """Extract 3yr/5yr risk and return statistics."""
    rstat = {}
    for metric, key in [
        ("Standard Deviation",  "std_dev"),
        ("Arithmetic Mean",     "arithmetic_mean"),
        ("Sharpe Ratio",        "sharpe"),
        ("Alpha",               "alpha"),
        ("Beta",                "beta"),
        ("R-Squared",           "r_squared"),
        ("Information Ratio",   "info_ratio"),
        ("Tracking Error",      "tracking_error"),
    ]:
        m = re.search(rf"{re.escape(metric)}\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            rstat[key] = {
                "metric":   metric,
                "3yr":      safe_float(m.group(1)),
                "5yr":      safe_float(m.group(2)),
            }
    return rstat


# ---------------------------------------------------------------------------
# Main parser
# ---------------------------------------------------------------------------
def parse_xray(pdf_path: str) -> dict:
    text = extract_all_text(pdf_path)

    report_date = parse_report_date(text)

    # Derive month label
    month_label = "unknown"
    try:
        dt = datetime.strptime(report_date, "%d-%b-%Y")
        month_label = dt.strftime("%b_%Y").lower()
    except ValueError:
        pass

    PARSE_WARNINGS.clear()   # A10 — per-run warning capture (parsers below append)
    result = {
        "_meta": {
            "source_file":    os.path.basename(pdf_path),
            "report_date":    report_date,
            "month_label":    month_label,
            "extracted_at":   datetime.now().strftime("%Y-%m-%d %H:%M"),
        },
        "asset_allocation": parse_asset_allocation(text),
        "country_exposure":  parse_country_exposure(text),
        "world_regions":     parse_world_regions(text),
        "sector_weights":    parse_sector_weights(text),
        "investment_style":  parse_investment_style(text),
        "trailing_returns":  parse_trailing_returns(text),
        "risk_statistics":   parse_rstat(text),
        "fund_holdings":     parse_fund_holdings(text),
    }
    result["_meta"]["parse_warnings"] = list(PARSE_WARNINGS)   # Fix Pack A10

    # Validation
    warnings = []
    if not result["sector_weights"]:
        warnings.append("sector_weights: no data extracted — check PDF format")
    if not result["trailing_returns"]:
        warnings.append("trailing_returns: no data extracted")
    if not result["fund_holdings"]:
        warnings.append("fund_holdings: no data extracted — check PDF format")
    if warnings:
        result["_warnings"] = warnings

    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Extract AJ Bell ISA X-Ray PDF to structured JSON."
    )
    parser.add_argument("--pdf", default=None,
                        help="Path to X-Ray PDF. Auto-detects latest if omitted.")
    parser.add_argument("--out", default=None,
                        help="Output JSON path. Defaults to xray_data_mmm_yyyy.json.")
    parser.add_argument("--isa-folder", default=ISA_FOLDER)
    args = parser.parse_args()

    if args.pdf:
        pdf_path = args.pdf
        if not os.path.exists(pdf_path):
            print(f"ERROR: PDF not found: {pdf_path}")
            sys.exit(1)
    else:
        try:
            pdf_path = find_latest_xray(args.isa_folder)
        except FileNotFoundError as e:
            print(f"ERROR: {e}")
            sys.exit(1)
        print(f"Auto-detected: {os.path.basename(pdf_path)}")

    print(f"Parsing: {pdf_path}")
    try:
        data = parse_xray(pdf_path)
    except Exception as e:
        print(f"ERROR parsing X-Ray PDF: {e}")
        sys.exit(1)

    # Output
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if args.out:
        out_path = args.out
    else:
        month_label = data["_meta"]["month_label"]
        out_path = os.path.join(script_dir, f"xray_data_{month_label}.json")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    # Summary
    print(f"\nX-Ray extracted: {data['_meta']['report_date']}")
    sw = data.get("sector_weights", {})
    print(f"  Sectors extracted:  {len(sw)}")
    tr = data.get("trailing_returns", {})
    if "1yr" in tr:
        r = tr["1yr"]
        print(f"  1yr return:         {r.get('portfolio_pct','?')}% portfolio vs {r.get('benchmark_pct','?')}% benchmark")
    fh = data.get("fund_holdings", [])
    print(f"  Fund holdings rows: {len(fh)}")
    if data.get("_warnings"):
        print(f"\n  WARNINGS:")
        for w in data["_warnings"]:
            print(f"    - {w}")
    print(f"\nOutput written: {out_path}")
    return out_path


if __name__ == "__main__":
    main()
