#!/usr/bin/env python3
"""
extract_xray.py  --  AJ Bell ISA Portfolio X-Ray PDF parser
Version: 1.0  |  2026-05-31

Reads the latest AJ Bell ISA Portfolio X-Ray PDF from the ISA folder and produces
a clean xray_data_mmm_yyyy.json. Called by monthly_isa_prerun.py.

Usage (standalone):
    python3 extract_xray.py [--pdf /path/to/file.pdf] [--out /path/to/output.json]

Output: xray_data_mmm_yyyy.json with:
  - Asset allocation (stocks, bonds, cash, other)
  - Geographic/country exposure (vs benchmark)
  - World region breakdown (vs benchmark)
  - Stock sector weights (vs benchmark)
  - Investment style box
  - Trailing performance (3m, 6m, 1yr, 3yr, 5yr, YTD)
  - Per-fund holdings table (name, Morningstar rating, 1yr/3yr/5yr returns, weight %, TER)

PDF format: Morningstar Portfolio X-Ray as generated by AJ Bell.
Parsing uses a combination of pdfplumber text extraction and regex.
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime

import pdfplumber


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
ISA_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# Morningstar star rating — AJ Bell PDF uses "Q" for stars
MS_RATING_MAP = {"QQQQQ": 5, "QQQQ": 4, "QQQ": 3, "QQ": 2, "Q": 1}

# Known sector codes in X-Ray PDF
SECTOR_MAP = {
    "Basic Materials":       "basic_materials",
    "Communication Services":"communication_services",
    "Consumer Cyclical":     "consumer_cyclical",
    "Consumer Defensive":    "consumer_defensive",
    "Energy":                "energy",
    "Financial Services":    "financial_services",
    "Healthcare":            "healthcare",
    "Industrials":           "industrials",
    "Real Estate":           "real_estate",
    "Technology":            "technology",
    "Utilities":             "utilities",
}

_SECTOR_NAME = {v: k for k, v in SECTOR_MAP.items()}


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------
def find_latest_xray(folder: str) -> str:
    """Find latest AJ Bell ISA Portfolio X-Ray PDF (not 'End of Tax Year')."""
    pattern = os.path.join(folder, "AJ Bell ISA Portfolio X-Ray *.pdf")
    candidates = [
        f for f in glob.glob(pattern)
        if "end of tax year" not in os.path.basename(f).lower()
    ]
    if not candidates:
        raise FileNotFoundError(
            f"No AJ Bell ISA Portfolio X-Ray PDF found in: {folder}\n"
            f"Expected filename: 'AJ Bell ISA Portfolio X-Ray DD-Mmm-YY.pdf'"
        )

    def _parse_date(path):
        name = os.path.basename(path)
        m = re.search(r"(\d{2}-\w{3}-\d{2,4})\.pdf$", name, re.IGNORECASE)
        if m:
            for fmt in ("%d-%b-%y", "%d-%b-%Y"):
                try:
                    return datetime.strptime(m.group(1), fmt)
                except ValueError:
                    pass
        return datetime.min

    return max(candidates, key=_parse_date)


# ---------------------------------------------------------------------------
# Text extraction helpers
# ---------------------------------------------------------------------------
def extract_all_text(pdf_path: str) -> str:
    """Extract all text from PDF, one page at a time, joined with newlines."""
    pages = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            t = page.extract_text() or ""
            pages.append(t)
    return "\n\n".join(pages)


def safe_float(s: str) -> float | None:
    """Convert string to float, return None on failure."""
    if s is None:
        return None
    s = str(s).strip().replace(",", "").replace("%", "")
    if s in ("", "-", "—", "N/A", "n/a"):
        return None
    try:
        return float(s)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Parser sections
# ---------------------------------------------------------------------------
def parse_report_date(text: str) -> str:
    m = re.search(r"Report as of\s+(\d+\s+\w+\s+\d{4})", text)
    if m:
        try:
            dt = datetime.strptime(m.group(1), "%d %B %Y")
            return dt.strftime("%d-%b-%Y")
        except ValueError:
            return m.group(1)
    m2 = re.search(r"Date\s*:\s*(\w+\s+\d+\s+\d{4})", text)
    if m2:
        try:
            dt = datetime.strptime(m2.group(1), "%B %d %Y")
            return dt.strftime("%d-%b-%Y")
        except ValueError:
            return m2.group(1)
    return "unknown"


def parse_asset_allocation(text: str) -> dict:
    """Extract asset allocation percentages from X-Ray page 2 text."""
    result = {}
    # Pattern: "Stocks 90.31 0.05 90.26"
    for asset in ["Stocks", "Bonds", "Cash", "Other", "Not classified"]:
        m = re.search(
            rf"{re.escape(asset)}\s+([\d.]+)\s+([\d.]+)\s+([\-\d.]+)", text
        )
        if m:
            key = asset.lower().replace(" ", "_")
            result[key] = {
                "long_pct":  safe_float(m.group(1)),
                "short_pct": safe_float(m.group(2)),
                "net_pct":   safe_float(m.group(3)),
            }
    return result


# Fix Pack A10 (P2): STATIC country whitelist — the old catch-all [A-Z][a-z]+ arm ingested
# header/label rows as data ("June" 2026.0, "Benchmark" rows). Whitelist + 0-100 pct-range
# validation; rejected rows land in PARSE_WARNINGS (surfaced via _meta.parse_warnings and the
# pre-run schema assert). "Other"/"Others" is a legitimate residual row and is included.
COUNTRY_WHITELIST = frozenset([
    "United States", "United Kingdom", "Japan", "China", "France", "Taiwan",
    "Republic of Korea", "South Korea", "Spain", "Italy", "Germany", "Canada",
    "Australia", "Netherlands", "Switzerland", "Sweden", "Denmark", "Norway",
    "Finland", "India", "Brazil", "Hong Kong", "Singapore", "Mexico", "Belgium",
    "Austria", "Ireland", "Portugal", "Israel", "New Zealand", "South Africa",
    "Indonesia", "Malaysia", "Thailand", "Philippines", "Vietnam", "Poland",
    "Turkey", "Greece", "Chile", "Colombia", "Peru", "Argentina", "Saudi Arabia",
    "United Arab Emirates", "Qatar", "Kuwait", "Egypt", "Luxembourg", "Iceland",
    "Other", "Others",
])

PARSE_WARNINGS: list = []   # A10 — reset per extract run; copied into _meta.parse_warnings


def _valid_pct(v):
    return v is None or (isinstance(v, (int, float)) and 0.0 <= v <= 100.0)


def parse_country_exposure(text: str) -> list:
    """
    Extract country exposure table. Returns list of
    {country, equity_pct, benchmark_pct}.
    A10: whitelist countries; reject pct outside 0-100; rejected rows -> PARSE_WARNINGS.
    """
    countries = []
    # Lines like: "United States 40.03 65.85" (two side-by-side columns in PDF text)
    pattern = re.compile(
        r"([A-Z][A-Za-z]+(?:\s[A-Za-z][A-Za-z]+){0,3})"
        r"\s+([\d.]+)\s+([\d.]+)"
    )
    for m in pattern.finditer(text):
        name = m.group(1).strip()
        eq, bench = safe_float(m.group(2)), safe_float(m.group(3))
        if name not in COUNTRY_WHITELIST:
            # header/label/date rows are EXPECTED matches of the loose pattern — only warn on
            # rows that look plausibly geographic (both pcts in range) so the warning list
            # stays signal, not noise
            if _valid_pct(eq) and _valid_pct(bench) and eq is not None:
                PARSE_WARNINGS.append(f"country row rejected (not whitelisted): {name!r} {eq}/{bench}")
            continue
        if not (_valid_pct(eq) and _valid_pct(bench)):
            PARSE_WARNINGS.append(f"country row rejected (pct out of 0-100): {name!r} {eq}/{bench}")
            continue
        countries.append({
            "country":       name,
            "equity_pct":    eq,
            "benchmark_pct": bench,
        })
    # Deduplicate (PDF may repeat entries)
    seen = set()
    unique = []
    for c in countries:
        k = c["country"]
        if k not in seen:
            seen.add(k)
            unique.append(c)
    return unique


# ISA-0367. The X-Ray's world-region block is a TREE: the three continent nodes contain
# the country/sub-region nodes beneath them, which is why the block sums to ~177pp. It is
# declared here once so no consumer has to infer it (one home per rule).
WORLD_REGION_PARENT = {
    "united_kingdom":          "greater_europe",
    "western_europe":          "greater_europe",
    "emerging_europe":         "greater_europe",
    "middle_east___africa":    "greater_europe",
    "united_states":           "americas",
    "canada":                  "americas",
    "central_and_latin_america": "americas",
    "japan":                   "greater_asia",
    "australasia":             "greater_asia",
    "emerging_4_tigers":       "greater_asia",
    "emerging_asia":           "greater_asia",
    "greater_europe":          None,
    "americas":                None,
    "greater_asia":            None,
}
WORLD_REGION_DEPTH = {k: (0 if v is None else 1) for k, v in WORLD_REGION_PARENT.items()}
WORLD_REGION_LEAVES = frozenset(k for k, v in WORLD_REGION_PARENT.items() if v is not None)


class RegionHierarchyError(ValueError):
    """The world-region tree does not reconcile: a parent does not equal the sum of its
    children (ISA-0367). Three sub-regions were silently absent for eight months --
    Western Europe (printed as two wrapped rows, 'Western Europe - Euro' and
    '... - Non Euro'), Central & Latin America and Emerging Asia - Ex 4 Tigers -- because
    each printed label carries a trailing fragment the old fixed-name regex could not
    match. Nothing checked that the children reconciled to the parent, so 14.17pp of
    Greater Europe, 1.09pp of the Americas and 7.32pp of Greater Asia read as absent
    exposure rather than unread exposure."""


# The printed label(s) that carry each region's numbers. A tuple means the region is
# printed as more than one row (Western Europe is split Euro / Non-Euro) and the rows are
# SUMMED -- summing rows that share a parent is order-independent, so no layout
# assumption is encoded (ISA-0367).
REGION_PATTERNS = {
    "greater_europe":            (r"Greater Europe",),
    "americas":                  (r"Americas",),
    "greater_asia":              (r"Greater Asia",),
    "united_kingdom":            (r"United Kingdom",),
    "western_europe":            (r"Western Europe\s*-",),
    "emerging_europe":           (r"Emerging Europe",),
    "middle_east___africa":      (r"Middle East\s*/\s*Africa", r"Middle East"),
    "united_states":             (r"United States",),
    "canada":                    (r"Canada",),
    "central_and_latin_america": (r"Central & Latin",),
    "japan":                     (r"Japan",),
    "australasia":               (r"Australasia",),
    "emerging_4_tigers":         (r"Emerging 4 Tigers",),
    "emerging_asia":             (r"Emerging Asia\s*-?\s*Ex",),
}
_REGION_DISPLAY = {
    "greater_europe": "Greater Europe", "americas": "Americas", "greater_asia": "Greater Asia",
    "united_kingdom": "United Kingdom", "western_europe": "Western Europe",
    "emerging_europe": "Emerging Europe", "middle_east___africa": "Middle East / Africa",
    "united_states": "United States", "canada": "Canada",
    "central_and_latin_america": "Central & Latin America", "japan": "Japan",
    "australasia": "Australasia", "emerging_4_tigers": "Emerging 4 Tigers",
    "emerging_asia": "Emerging Asia - Ex 4 Tigers",
}
REGION_ROLLUP_TOL_PP = 0.11   # 3-4 rounded children against a rounded parent


def _region_block(text: str) -> str:
    """The World Regions block only. 'United Kingdom' also appears in the country
    exposure table further down the document, so a whole-document findall double-counts
    it -- the same whole-document-search cause as the sector defect (ISA-0367)."""
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        if re.search(r"\bWorld Regions?\b", ln):
            return "\n".join(lines[i:i + 16])
    raise RegionHierarchyError(
        "world_regions: no 'World Regions' block found in the X-Ray text -- the PDF "
        "layout has changed and the region tree must not be guessed at")


def parse_world_regions(text: str) -> dict:
    """Extract the world-region breakdown as a RECONCILED TREE.

    Returns {region_key: {name, equity_pct, benchmark_pct, depth, parent, is_leaf}} plus
    a `_structure` node. Raises RegionHierarchyError when a parent does not equal the sum
    of its children -- which is the only thing that can detect a sub-region the PDF
    printed and the parser did not read (ISA-0367).
    """
    block = _region_block(text)
    regions = {}
    for key, pats in REGION_PATTERNS.items():
        eq = bench = None
        rows = 0
        for pat in pats:
            found = re.findall(pat + r"\s+(\d+\.\d+)\s+(\d+\.\d+)", block)
            if found:
                eq = sum(safe_float(a) or 0.0 for a, _ in found)
                bench = sum(safe_float(b) or 0.0 for _, b in found)
                rows = len(found)
                break
        if eq is None:
            continue
        regions[key] = {
            "name":          _REGION_DISPLAY[key],
            "equity_pct":    round(eq, 2),
            "benchmark_pct": round(bench, 2),
            # ISA-0367: this dimension is a TREE, not a partition. `depth`/`parent` travel
            # with every node so no consumer can sum it by accident -- the whole block
            # sums to ~177pp precisely because parents contain their children.
            "depth":         WORLD_REGION_DEPTH.get(key, 0),
            "parent":        WORLD_REGION_PARENT.get(key),
            "is_leaf":       key in WORLD_REGION_LEAVES,
            "printed_rows":  rows,
        }

    # THE HIERARCHY CONTRACT. Every parent must equal the sum of its children on BOTH
    # columns. This is the tree's version of the sector tiling contract, and it is what
    # makes an unread sub-region impossible to mistake for a zero exposure.
    breaches = []
    for parent in (k for k, v in WORLD_REGION_PARENT.items() if v is None):
        if parent not in regions:
            continue
        kids = [k for k, v in WORLD_REGION_PARENT.items() if v == parent and k in regions]
        for col in ("equity_pct", "benchmark_pct"):
            got = sum(regions[k][col] for k in kids)
            want = regions[parent][col]
            if abs(got - want) > REGION_ROLLUP_TOL_PP:
                breaches.append("%s.%s: children sum to %.2f, parent prints %.2f "
                                "(children read: %s)" % (parent, col, got, want, kids))
    if breaches:
        raise RegionHierarchyError(
            "world_regions does not reconcile -- an unread sub-region is not a zero "
            "exposure:\n  - " + "\n  - ".join(breaches))

    leaf_total = {c: round(sum(v[c] for k, v in regions.items() if v["is_leaf"]), 2)
                  for c in ("equity_pct", "benchmark_pct")}
    regions["_structure"] = {
        "kind":            "hierarchy",
        "is_partition":    False,
        "note":            ("world_regions is HIERARCHICAL (americas contains united_states "
                            "and canada, and so on) and the whole block sums to ~177pp. Do "
                            "NOT sum it. world_regions_partition() returns the depth-0 "
                            "continents and world_regions_leaves() the depth-1 sub-regions; "
                            "each of those IS a partition and each is asserted to reconcile "
                            "to the other."),
        "leaf_keys":       sorted(k for k, v in regions.items() if k != "_structure" and v["is_leaf"]),
        "partition_keys":  sorted(k for k, v in regions.items() if k != "_structure" and not v["is_leaf"]),
        "leaf_total":      leaf_total,
        "reconciled":      True,
    }
    return regions


def world_regions_partition(regions: dict) -> dict:
    """The depth-0 (continent) partition of the hierarchical world_regions block."""
    return {k: v for k, v in (regions or {}).items()
            if isinstance(v, dict) and v.get("depth") == 0}


def world_regions_leaves(regions: dict) -> dict:
    """The depth-1 (sub-region) partition of the hierarchical world_regions block."""
    return {k: v for k, v in (regions or {}).items()
            if isinstance(v, dict) and v.get("is_leaf")}


class SectorPartitionError(ValueError):
    """Raised when the Stock Sectors block cannot be read as a complete partition.

    ISA-0367 (19-Aug-2026). The previous parser searched the WHOLE document once per
    canonical sector name and took the first match. Two consequences, both silent:

      * a label the PDF's 3-column layout had truncated ("Communicatio" for
        "Communication Services") matched nothing and the sector was simply ABSENT,
        so a 6.50% exposure read as a 0% exposure;
      * two rows whose visible label was the same truncated word ("Consumer", twice)
        both resolved to the FIRST match, so consumer_cyclical and consumer_defensive
        were both written with 4.72/4.51 when the true cyclical figures are 9.62/8.68.

    Every individual number stayed plausible, which is why eight months of runs did not
    notice. The evidence sat in PARSE_WARNINGS the whole time and nothing read it
    (R4.12: audit trails are EXERCISED, not merely recorded).

    The fix is a CONTRACT, not a hand-patch of one month's values: the block is read
    POSITIONALLY, each canonical sector may be assigned at most once, the eleven
    sectors must tile the book on BOTH columns, and the assignment must reproduce the
    PDF's own Cyclical/Sensitive/Defensive super-sector totals (two independent
    derivations must agree). Ambiguity is RESOLVED by that second derivation rather
    than by document order, so no month's layout is encoded as a rule.
    """


# Morningstar super-sectors. The X-Ray prints these three totals on its own line, which
# makes them an INDEPENDENT derivation of the same eleven numbers -- used both to
# disambiguate truncated labels and to assert the finished vector (ISA-0367).
SUPER_SECTORS = {
    "Cyclical":  ("basic_materials", "consumer_cyclical", "financial_services", "real_estate"),
    "Sensitive": ("communication_services", "energy", "industrials", "technology"),
    "Defensive": ("consumer_defensive", "healthcare", "utilities"),
}

SECTOR_TILING_TOL_PP = 1.50   # 11 rounded rows against 100; observed residual 0.15-0.68pp
SECTOR_ROLLUP_TOL_PP = 0.15   # super-sector rollup against the PDF's own printed total
_SECTOR_MIN_FRAGMENT = 5      # a label fragment shorter than this cannot identify a sector


def _sector_block(text: str) -> str:
    """The Stock Sectors block only. Bounding the search is what makes the parse
    positional rather than document-wide -- the whole-document re.search is the
    proximate cause of ISA-0367."""
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        if re.search(r"\bStock Sectors?\b", ln):
            return "\n".join(lines[i:i + 20])
    raise SectorPartitionError(
        "sector_weights: no 'Stock Sectors' block found in the X-Ray text -- "
        "the PDF layout has changed and the sector vector must not be guessed at")


def _sector_candidates(label):
    """Canonical sectors this (icon-prefixed, possibly truncated) label fragment could
    name. Returns (longest_matching_fragment, {keys})."""
    toks = label.split()
    best = ("", set())
    for i in range(len(toks)):
        frag = " ".join(toks[i:])
        for variant in (frag, frag[1:]):      # the PDF glues a 1-char icon glyph to the label
            variant = variant.strip()
            if len(variant) < _SECTOR_MIN_FRAGMENT:
                continue
            hits = {k for name, k in SECTOR_MAP.items() if name.startswith(variant)}
            if hits and len(variant) > len(best[0]):
                best = (variant, hits)
    return best


def _parse_super_sectors(block):
    out = {}
    for name in SUPER_SECTORS:
        m = re.search(name + r"\s+(\d+\.\d+)\s+(\d+\.\d+)", block)
        if m:
            out[name] = (float(m.group(1)), float(m.group(2)))
    return out


def _rollup_ok(assigned, supers):
    for name, members in SUPER_SECTORS.items():
        if name not in supers:
            continue
        if any(m not in assigned for m in members):
            return False
        for idx, col in enumerate(("portfolio_pct", "benchmark_pct")):
            got = sum(assigned[m][col] for m in members)
            if abs(got - supers[name][idx]) > SECTOR_ROLLUP_TOL_PP:
                return False
    return True


def parse_sector_weights(text: str) -> dict:
    """Extract stock sector weights vs benchmark as a VERIFIED PARTITION.

    Returns {sector_key: {name, portfolio_pct, benchmark_pct, vs_benchmark}}.
    Raises SectorPartitionError rather than returning a short or double-written vector
    (ISA-0367) -- an unread sector is not a zero exposure.
    """
    block = _sector_block(text)

    rows = []
    for m in re.finditer(r"([A-Za-z][A-Za-z&/.\- ]*?)\s+(\d+\.\d+)\s+(\d+\.\d+)", block):
        frag, hits = _sector_candidates(m.group(1).strip())
        if hits:
            rows.append({"frag": frag, "hits": hits,
                         "p": float(m.group(2)), "b": float(m.group(3))})

    assigned, ambiguous, claimed = {}, [], set()
    for r in rows:
        if len(r["hits"]) == 1:
            k = next(iter(r["hits"]))
            if k in claimed:
                raise SectorPartitionError(
                    "sector_weights: %s matched two rows in the Stock Sectors block "
                    "(%s and %s). A sector may be assigned at most once -- writing the "
                    "first match twice is ISA-0367."
                    % (k, assigned[k]["portfolio_pct"], r["p"]))
            claimed.add(k)
            assigned[k] = {"name": _SECTOR_NAME[k], "portfolio_pct": r["p"],
                           "benchmark_pct": r["b"]}
        else:
            ambiguous.append(r)

    supers = _parse_super_sectors(block)
    if ambiguous:
        if not supers:
            raise SectorPartitionError(
                "sector_weights: rows with ambiguous truncated labels %s and no "
                "Cyclical/Sensitive/Defensive line to resolve them against -- refusing "
                "to guess by document order" % [r["frag"] for r in ambiguous])
        import itertools
        open_keys = sorted({k for r in ambiguous for k in r["hits"]} - claimed)
        viable = []
        for perm in itertools.permutations(open_keys, len(ambiguous)):
            if any(k not in r["hits"] for k, r in zip(perm, ambiguous)):
                continue
            trial = dict(assigned)
            for k, r in zip(perm, ambiguous):
                trial[k] = {"name": _SECTOR_NAME[k], "portfolio_pct": r["p"],
                            "benchmark_pct": r["b"]}
            if _rollup_ok(trial, supers):
                viable.append(perm)
        if len(viable) != 1:
            raise SectorPartitionError(
                "sector_weights: %d assignments of the ambiguous rows %s reproduce the "
                "printed super-sector totals %s; exactly one is required"
                % (len(viable), [r["frag"] for r in ambiguous], supers))
        for k, r in zip(viable[0], ambiguous):
            assigned[k] = {"name": _SECTOR_NAME[k], "portfolio_pct": r["p"],
                           "benchmark_pct": r["b"]}

    # THE TILING CONTRACT -- a dimension declared as a partition must tile the book on
    # BOTH columns and carry every declared member. A short vector renormalises every
    # consumer's denominator invisibly, which is why eight months of it went unseen.
    missing = [k for k in SECTOR_MAP.values() if k not in assigned]
    if missing:
        raise SectorPartitionError(
            "sector_weights: %d sector(s) absent from the parse: %s. An unread sector "
            "is not a zero exposure." % (len(missing), missing))
    for col, lab in (("portfolio_pct", "portfolio"), ("benchmark_pct", "benchmark")):
        tot = sum(v[col] for v in assigned.values())
        if abs(tot - 100.0) > SECTOR_TILING_TOL_PP:
            raise SectorPartitionError(
                "sector_weights: the %s column sums to %.2f, outside 100 +/- %.2fpp -- "
                "the sector vector does not tile the book" % (lab, tot, SECTOR_TILING_TOL_PP))
    if supers and not _rollup_ok(assigned, supers):
        raise SectorPartitionError(
            "sector_weights: the parsed sectors do not reproduce the X-Ray's own "
            "Cyclical/Sensitive/Defensive totals %s within %.2fpp"
            % (supers, SECTOR_ROLLUP_TOL_PP))

    for v in assigned.values():
        v["vs_benchmark"] = round(v["portfolio_pct"] - v["benchmark_pct"], 2)
    return {k: assigned[k] for k in SECTOR_MAP.values()}


def parse_trailing_returns(text: str) -> dict:
    """
    Extract trailing returns table.
    Returns {period: {portfolio_pct, benchmark_pct, relative_pct}}.
    """
    returns = {}
    periods = {
        "3 Months":           "3m",
        "6 Months":           "6m",
        "1 Year":             "1yr",
        "3 Years Annualised": "3yr_ann",
        "5 Years Annualised": "5yr_ann",
        "YTD":                "ytd",
    }
    for label, key in periods.items():
        m = re.search(
            rf"{re.escape(label)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if m:
            port  = safe_float(m.group(1))
            bench = safe_float(m.group(2))
            rel   = round((port or 0) - (bench or 0), 2) if port is not None and bench is not None else None
            returns[key] = {
                "period":        label,
                "portfolio_pct": port,
                "benchmark_pct": bench,
                "relative_pct":  rel,
            }
    return returns



_MONTHS = {m.lower(): i for i, m in enumerate(
    ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], 1)}


def _parse_fund_as_of(raw):
    """'30 Jun 2026' -> '2026-06-30'. D1: this date is the ONLY honest statement
    of when a per-fund return was struck, and it is routinely a month behind the
    report header. Returning None is fine -- the caller flags it -- but silently
    inheriting the header date is not."""
    if not raw:
        return None
    parts = raw.split()
    if len(parts) != 3:
        return None
    try:
        day = int(parts[0]); mon = _MONTHS.get(parts[1][:3].lower()); yr = int(parts[2])
        return f"{yr:04d}-{mon:02d}-{day:02d}" if mon else None
    except (ValueError, TypeError):
        return None


def stamp_fund_staleness(funds, report_date):
    """I4 -- every per-fund figure must declare how stale it is vs the report
    header. Returns (funds, warnings). A gap is NOT an error (Morningstar lags
    by design); publishing it undated IS."""
    import datetime as _dt
    warnings = []
    try:
        rep = _dt.date.fromisoformat((report_date or "")[:10])
    except (ValueError, TypeError):
        rep = None
    worst = 0
    for f in funds:
        if f.get("as_of") and rep:
            try:
                d = (rep - _dt.date.fromisoformat(f["as_of"])).days
            except ValueError:
                d = None
            f["stale_days"] = d
            f["as_of_basis"] = "per-fund Date column (NOT the report header)"
            if d and d > 5:
                worst = max(worst, d)
        else:
            f["stale_days"] = None
            f["as_of_basis"] = "UNKNOWN -- no per-fund date parsed"
            warnings.append(f"I4: '{f.get('name','?')}' has no per-fund as_of; "
                            "its returns must NOT be presented as current")
    if worst:
        warnings.append(
            f"I4: X-Ray per-fund performance is {worst} days older than the report "
            f"date {report_date}. These are CORROBORATORS only -- fund_performance.py "
            f"is the golden source. Render as 'x.xx% (as at <date>)', never bare.")
    return funds, warnings



def parse_holdings_statistics(text: str) -> dict:
    """Per-fund **Mean** and **Std Dev** from the `Portfolio Holdings Statistics` table.

    ⚑ NOT PARSED AT ALL BEFORE 05-Aug-2026, and it is the table register item H7 is built on
    ("RLGES 17.73/13.77 vs VUAG 18.01/13.37"). Without it the framework could quote H7 but not
    reproduce, re-test or refresh it.

    ⚑ AND ITS WINDOW IS UNSTATED. The columns are headed only `Name Assets Mean Std Dev` — no
    period. The window was identified as **3 YEARS** by reconciling the published std devs
    against NAV-derived figures (VUAG 13.37 vs a 3y 13.24-13.43 and a 5y 13.09; RLGES 13.77 vs
    a 3y 13.62 and a 5y 13.04; same conclusion on Ranmore and Thornbridge). It is recorded as
    `window_basis: "inferred_3y"` — inferred, and labelled as inferred, because a number whose
    period is assumed is exactly the semantic-drift class this framework keeps paying for.
    **This matters: the VUAG-vs-RLGES dominance verdict REVERSES between the 3y and 5y windows.**
    """
    out = {"funds": {}, "order": [], "by_index": {}, "missing_indices": [],
           "window_basis": "inferred_3y",
           "window_note": ("the source table states no period; 3 years identified by "
                           "reconciling published std devs against NAV-derived 3y and 5y "
                           "figures across four funds")}
    i = text.find("Portfolio Holdings Statistics")
    if i == -1:
        return out
    seg = text[i:i + 4000]
    # The RIGHT-HAND statistics panel bleeds onto the same physical line for several rows
    # ("... 11.75 18.01 13.37 Standard Deviation 12.99 12.75"), so anchoring at end-of-line
    # dropped 7 of 13 funds — including, again, VUAG.
    row = re.compile(r"^\s*(\d+)\s+([A-Za-z][A-Za-z0-9 &\-\.\'()\u00a3/]+?)\s+"
                     r"([\d.]+)\s+([\d.]+|-)\s+([\d.]+|-)(?:\s|$)", re.M)
    for m in row.finditer(seg):
        idx = int(m.group(1))
        name = m.group(2).strip()
        if len(name) < 4:
            continue
        out["funds"][name] = {
            "row_index": idx,
            "assets_pct": safe_float(m.group(3)),
            "mean": safe_float(m.group(4)),
            "std_dev": safe_float(m.group(5)),
        }
        out["by_index"][idx] = name
        out["order"].append(name)
    # ⚑ THE PRINTED ROW NUMBER IS THE KEY, NOT THE POSITION IN THIS LIST. The Correlation Matrix
    # is indexed against THESE row numbers and carries no fund names of its own. Row 6 is
    # "Cash GBP", whose lowercase letters the original all-caps name pattern rejected — so a
    # positional mapping silently closed the gap and shifted rows 7-10 up by one, handing Royal
    # London's 0.91 correlation with VUAG to MI Thornbridge. That single number is the entire
    # basis of register H7's fee argument. Any missing index is now RECORDED, and the correlation
    # mapping refuses the affected rows rather than sliding.
    seen = sorted(out["by_index"])
    if seen:
        out["missing_indices"] = [i for i in range(1, max(seen) + 1) if i not in out["by_index"]]
        if out["missing_indices"]:
            PARSE_WARNINGS.append(
                f"holdings_statistics: row indices {out['missing_indices']} did not parse "
                f"(typically the 'Cash GBP' row). Recorded, so the correlation matrix cannot "
                f"map across the gap.")
    return out


def parse_lookthrough_top10(text: str) -> dict:
    """H10 — the `Top 10 Underlying Holdings` table: portfolio-level LOOK-THROUGH exposure.

    ⚑ NEVER PARSED BEFORE (06-Aug-2026), and the framework was hand-computing the same numbers
    and getting them wrong. `portfolio_analytics.build_overlap_check_structure` asked Claude to
    look up each stock in each fund's top ten and add it to the direct weight by hand. On the
    August run that produced **AVGO 4.04%**, missing MI Thornbridge's 3.84% position. The X-Ray
    publishes the answer — **4.31%** — as a table, computed by Morningstar across the actual
    underlying holdings of every fund, which is a source the hand-calc could never match.

    A hand-computed figure that a machine-readable source already publishes is not a fallback,
    it is a second source of truth that will drift. Standard rule 5: one home per rule.

    ⚑ COVERAGE IS EXPLICIT. This is the top TEN only, so a name below the tenth is UNKNOWN, not
    zero. `covered_pct` is reported so the difference is impossible to overlook: on August data
    the ten names cover 18.12% of the portfolio and the other ~82% is simply not in this table.
    """
    out = {"holdings": [], "covered_pct": None, "source_table": "Top 10 Underlying Holdings",
           "coverage_note": ("TOP TEN ONLY. A name absent from this table is UNRANKED, not "
                             "absent from the portfolio — treating absence as zero exposure is "
                             "the single easiest way to under-read a concentration.")}
    i = text.find("Top 10 Underlying Holdings")
    if i == -1:
        PARSE_WARNINGS.append("lookthrough_top10: section header not found")
        return out
    seg = text[i:i + 2500]
    # "4.31 Broadcom Inc Stock Technology United States"
    # ⚑ SECTOR IS MATCHED AGAINST A CLOSED VOCABULARY, not "everything up to the last words".
    # A greedy split read "Communication Services United States" as sector "Communication" and
    # country "Services United States", and "Consumer Cyclical United States" the same way — two
    # of the ten rows silently mangled, in a table whose entire purpose is naming exposures.
    sectors = sorted(set(SECTOR_MAP.values()) | {
        "Technology", "Communication Services", "Financial Services", "Consumer Cyclical",
        "Consumer Defensive", "Healthcare", "Industrials", "Basic Materials", "Energy",
        "Utilities", "Real Estate"}, key=len, reverse=True)
    row = re.compile(r"^\s*(\d+\.\d+)\s+(.+?)\s+(Stock|Equity|Bond|Cash|Fund|Other)\s+"
                     r"(" + "|".join(re.escape(x) for x in sectors) + r")\s+"
                     r"([A-Z][A-Za-z .'\-]+?)\s*$", re.M)
    for m in row.finditer(seg):
        pct = safe_float(m.group(1))
        name = m.group(2).strip()
        if pct is None or not name or len(name) < 2:
            continue
        out["holdings"].append({
            "name": name, "weight_pct": pct, "security_type": m.group(3).strip(),
            "sector": m.group(4).strip(), "country": m.group(5).strip()})
        if len(out["holdings"]) == 10:
            break
    if out["holdings"]:
        out["covered_pct"] = round(sum(h["weight_pct"] for h in out["holdings"]), 2)
        # ⚑ a monotonicity check, because a mis-parsed row is far more likely to break the
        # ordering than to look plausible: the table is published in descending weight.
        w = [h["weight_pct"] for h in out["holdings"]]
        if w != sorted(w, reverse=True):
            PARSE_WARNINGS.append(
                f"lookthrough_top10: rows are NOT in descending weight order {w} — the parse "
                f"has picked up something that is not a holdings row")
            out["order_warning"] = w
    else:
        PARSE_WARNINGS.append("lookthrough_top10: header found but NO rows parsed")
    if len(out["holdings"]) not in (0, 10):
        PARSE_WARNINGS.append(
            f"lookthrough_top10: parsed {len(out['holdings'])} rows from a table titled TOP 10 — "
            f"a partial parse of a fixed-size table is a parser fault, not a short table")
    return out


def parse_correlation_matrix(text: str, stats_names=None) -> dict:
    """The `Correlation Matrix` — a SECOND, INDEPENDENT derivation of the fund-fund correlations
    `fund_action_stack` computes from monthly NAV returns.

    Standard rule 4 asks for two derivations that must agree, and this is the only other one
    available. It matters immediately: the RLGES-vs-VUAG fee argument in register H7 rests on a
    correlation of **0.91**, which until now was a number quoted from a PDF nobody had parsed.

    ⚑ THE ROW LABELS ARE NUMBERS, NOT NAMES. The matrix is indexed 1..10 and the mapping to funds
    lives in the SEPARATE `Top 10 Portfolio Holdings Statistics` table, which is numbered the same
    way. So this parser REQUIRES that table's ordered names to be handed in; without them it
    returns the numeric matrix and NO fund mapping rather than assuming the order. Guessing an
    index-to-fund mapping is exactly how a correlation gets attached to the wrong pair — the same
    wrong-fund join that produced a false DISPUTED verdict in August.
    """
    out = {"matrix": {}, "index_to_fund": {}, "pairs": {}, "window_basis": "inferred_3y",
           "window_note": ("the matrix is printed beside a 3-Yr Mean / 3-Yr Standard Deviation "
                           "scatter and states no period of its own; 3 years is inferred from "
                           "that adjacency and labelled as inferred")}
    i = text.find("Correlation Matrix")
    if i == -1:
        return out
    seg = text[i:i + 2500]
    # ⚑ THE MATRIX SHARES ITS LINES WITH A SCATTER PLOT. Extracted text interleaves axis labels
    # and point markers with the matrix rows — row 3 arrives as "46 3 0.43 0.80 1.00" and row 8 as
    # "3 10 8 0.83 0.57 0.66 0.61 0.73 - 0.85 1.00". Anchoring the index at line start found only
    # rows 1, 2, 4, 7 and 10 and reported the rest as absent. The index is therefore the LAST
    # integer before the run of decimals, and the parse is validated structurally rather than
    # positionally: row n of a lower-triangular matrix has exactly n entries and its last is its
    # own diagonal. A mis-parse cannot satisfy that.
    row = re.compile(r"(\d{1,2})\s+((?:(?:-?\d\.\d{2}|-)\s+)*(?:-?\d\.\d{2}|-))\s*$", re.M)
    rejected = []
    for m in row.finditer(seg):
        idx = int(m.group(1))
        vals = [None if v == "-" else float(v) for v in m.group(2).split()]
        if len(vals) != idx:
            rejected.append({"index": idx, "n_values": len(vals)})
            continue
        if vals[-1] is not None and abs(vals[-1] - 1.00) > 1e-9:
            rejected.append({"index": idx, "diagonal": vals[-1]})
            continue
        out["matrix"][idx] = vals
    out["rejected_rows"] = rejected
    if out["matrix"]:
        got = sorted(out["matrix"])
        out["missing_rows"] = [i for i in range(1, max(got) + 1) if i not in out["matrix"]]
    if stats_names:
        # `stats_names` is an INDEX->NAME map from the statistics table's printed row numbers.
        # A plain ordered list is refused: it is the shape that produced the off-by-one above.
        if not isinstance(stats_names, dict):
            out["mapping_note"] = ("refused: an ordered LIST was supplied. The mapping must be "
                                   "keyed on the table's printed row numbers, because a dropped "
                                   "row (Cash GBP) shifts every fund after it.")
            return out
        out["index_to_fund"] = {int(k): v for k, v in stats_names.items()}
        for idx, vals in out["matrix"].items():
            for j, v in enumerate(vals, start=1):
                if v is None or j >= idx:
                    continue
                a, b = out["index_to_fund"].get(idx), out["index_to_fund"].get(j)
                if a and b:
                    out["pairs"][f"{a} | {b}"] = v
    else:
        out["mapping_note"] = ("no ordered fund list supplied, so the numeric indices are NOT "
                               "mapped to funds. An assumed order would attach a correlation to "
                               "the wrong pair, which is worse than having none.")
    return out


def parse_fund_holdings(text: str) -> list:
    """
    Extract Portfolio Holdings table (page 4 of PDF).
    Returns list of fund dicts.
    """
    funds = []

    # Find the holdings section
    holdings_start = text.find("Portfolio Holdings\nName Type Holding")
    if holdings_start == -1:
        holdings_start = text.find("Portfolio Holdings")
    if holdings_start == -1:
        return funds

    section = text[holdings_start:]

    # Each fund line (approximate):
    # "FUND NAME Type Date MS_RATING 1yr 3yr 5yr weight% TER OC"
    # Use a flexible pattern
    # ⚑ FIXED 05-Aug-2026. The name class excluded DIGITS and the POUND SIGN, and the type
    # alternation could not match a three-part type. Two holdings were therefore dropped
    # silently on every run:
    #     VANGUARD S&P 500 ETF USD ACC GBP     name contains "500"; type is "Mutual Fund - ETF"
    #     VANGUARD JPN STK IDX £ ACC           name contains "£"
    # Between them that is **16.2% of the portfolio, including the single largest holding at
    # 11.62%**, invisible to every X-Ray-derived check — which is precisely why the dominance
    # test could not adjudicate VUAG and reported it as having no second source.
    # A parser that drops a row it cannot match, without counting it, produces a table that
    # looks complete and is not.
    fund_pattern = re.compile(
        r"([A-Z][A-Z0-9 &\-\.\'()\u00a3/]+?)\s+"   # Fund name (caps, digits, GBP sign)
        # ⚑ The type cell WRAPS. VUAG's row reads "... GBP Mutual 30 Jun 2026 QQQQ ..." with
        # "Fund -" and "ETF" on the two FOLLOWING lines, so the type token on the data line is
        # the bare word "Mutual". Requiring "Mutual Fund" contiguous is why the largest holding
        # was dropped.
        r"(?:Mutual\s+Fund|Mutual|Fund|ETF|Cash)\s*"
        r"(?:\s*-\s*)?(?:ETF)?\s*"                 # optional " - ETF" continuation
        r"(\d+ \w+ \d{4})?\s*"                  # D1 FIX: the per-fund AS-AT DATE.
                                                 # This was NON-capturing -- the date the
                                                 # figures are actually struck at was parsed
                                                 # and DISCARDED, so month-old returns were
                                                 # published under the report header date.
        r"(Q{1,5}|-)\s*"                         # MS Rating (Q's or dash)
        r"([\d.]+|-)\s+"                          # 1yr
        r"([\d.]+|-)?\s*"                        # 3yr
        r"([\d.]+|-)?\s*"                        # 5yr
        r"([\d.]+)\s*"                           # weight %
        r"(-)\s*"                                # TER (always - in AJ Bell)
        r"([\d.]+|-)",                           # Ongoing cost
        re.IGNORECASE
    )

    for m in fund_pattern.finditer(section):
        name = m.group(1).strip()
        if len(name) < 5 or name.upper().startswith("NAME"):
            continue
        as_at_raw = (m.group(2) or "").strip()
        ms_str = m.group(3).strip()
        ms_rating = MS_RATING_MAP.get(ms_str) if ms_str != "-" else None

        fund_rec = {
            "name":         name,
            "as_of":        _parse_fund_as_of(as_at_raw),
            "as_of_raw":    as_at_raw or None,
            "ms_rating":    ms_rating,
            "return_1yr":   safe_float(m.group(4)),
            "return_3yr":   safe_float(m.group(5)),
            "return_5yr":   safe_float(m.group(6)),
            "weight_pct":   safe_float(m.group(7)),
            "ongoing_cost": safe_float(m.group(9)),
        }
        funds.append(fund_rec)

    # Deduplicate by name
    seen = set()
    unique = []
    for f in funds:
        k = f["name"][:20]
        if k not in seen:
            seen.add(k)
            unique.append(f)

    return unique


def parse_investment_style(text: str) -> dict:
    """Extract style box summary metrics."""
    style = {}
    for metric, key in [
        ("Price/Book Ratio",    "price_book"),
        ("Price/Earnings",      "price_earnings"),
        ("Price/Cashflow",      "price_cashflow"),
    ]:
        m = re.search(rf"{re.escape(metric)}\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            style[key] = {
                "portfolio":  safe_float(m.group(1)),
                "benchmark":  safe_float(m.group(2)),
            }
    return style


def parse_rstat(text: str) -> dict:
    """Extract 3yr/5yr risk and return statistics."""
    rstat = {}
    for metric, key in [
        ("Standard Deviation",  "std_dev"),
        ("Arithmetic Mean",     "arithmetic_mean"),
        ("Sharpe Ratio",        "sharpe"),
        ("Alpha",               "alpha"),
        ("Beta",                "beta"),
        ("R-Squared",           "r_squared"),
        ("Information Ratio",   "info_ratio"),
        ("Tracking Error",      "tracking_error"),
    ]:
        m = re.search(rf"{re.escape(metric)}\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            rstat[key] = {
                "metric":   metric,
                "3yr":      safe_float(m.group(1)),
                "5yr":      safe_float(m.group(2)),
            }
    return rstat


# ---------------------------------------------------------------------------
# Main parser
# ---------------------------------------------------------------------------
def parse_xray(pdf_path: str) -> dict:
    text = extract_all_text(pdf_path)

    report_date = parse_report_date(text)

    # Derive month label
    month_label = "unknown"
    try:
        dt = datetime.strptime(report_date, "%d-%b-%Y")
        month_label = dt.strftime("%b_%Y").lower()
    except ValueError:
        pass

    PARSE_WARNINGS.clear()   # A10 — per-run warning capture (parsers below append)
    result = {
        "_meta": {
            "source_file":    os.path.basename(pdf_path),
            "report_date":    report_date,
            "month_label":    month_label,
            "extracted_at":   datetime.now().strftime("%Y-%m-%d %H:%M"),
        },
        "asset_allocation": parse_asset_allocation(text),
        "country_exposure":  parse_country_exposure(text),
        "world_regions":     parse_world_regions(text),
        "sector_weights":    parse_sector_weights(text),
        "investment_style":  parse_investment_style(text),
        "trailing_returns":  parse_trailing_returns(text),
        "risk_statistics":   parse_rstat(text),
        "fund_holdings":     parse_fund_holdings(text),
        "holdings_statistics": parse_holdings_statistics(text),
        "lookthrough_top10": parse_lookthrough_top10(text),
    }
    result["correlation_matrix"] = parse_correlation_matrix(
        text, (result["holdings_statistics"] or {}).get("by_index"))
    result["_meta"]["parse_warnings"] = list(PARSE_WARNINGS)   # Fix Pack A10

    # Validation
    warnings = []
    if not result["sector_weights"]:
        warnings.append("sector_weights: no data extracted — check PDF format")
    if not result["trailing_returns"]:
        warnings.append("trailing_returns: no data extracted")
    if not result["fund_holdings"]:
        warnings.append("fund_holdings: no data extracted — check PDF format")
    if not (result.get("lookthrough_top10") or {}).get("holdings"):
        warnings.append("lookthrough_top10: no data extracted — the hand-calculated overlap it "
                        "replaces is WRONG (AVGO 4.04% vs the published 4.31%), so an absent "
                        "parse must be loud, not a quiet fallback")
    if warnings:
        result["_warnings"] = warnings

    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Extract AJ Bell ISA X-Ray PDF to structured JSON."
    )
    parser.add_argument("--pdf", default=None,
                        help="Path to X-Ray PDF. Auto-detects latest if omitted.")
    parser.add_argument("--out", default=None,
                        help="Output JSON path. Defaults to xray_data_mmm_yyyy.json.")
    parser.add_argument("--isa-folder", default=ISA_FOLDER)
    args = parser.parse_args()

    if args.pdf:
        pdf_path = args.pdf
        if not os.path.exists(pdf_path):
            print(f"ERROR: PDF not found: {pdf_path}")
            sys.exit(1)
    else:
        try:
            pdf_path = find_latest_xray(args.isa_folder)
        except FileNotFoundError as e:
            print(f"ERROR: {e}")
            sys.exit(1)
        print(f"Auto-detected: {os.path.basename(pdf_path)}")

    print(f"Parsing: {pdf_path}")
    try:
        data = parse_xray(pdf_path)
    except Exception as e:
        print(f"ERROR parsing X-Ray PDF: {e}")
        sys.exit(1)

    # Output
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if args.out:
        out_path = args.out
    else:
        month_label = data["_meta"]["month_label"]
        out_path = os.path.join(script_dir, f"xray_data_{month_label}.json")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    # Summary
    print(f"\nX-Ray extracted: {data['_meta']['report_date']}")
    sw = data.get("sector_weights", {})
    print(f"  Sectors extracted:  {len(sw)}")
    tr = data.get("trailing_returns", {})
    if "1yr" in tr:
        r = tr["1yr"]
        print(f"  1yr return:         {r.get('portfolio_pct','?')}% portfolio vs {r.get('benchmark_pct','?')}% benchmark")
    fh = data.get("fund_holdings", [])
    print(f"  Fund holdings rows: {len(fh)}")
    if data.get("_warnings"):
        print(f"\n  WARNINGS:")
        for w in data["_warnings"]:
            print(f"    - {w}")
    print(f"\nOutput written: {out_path}")
    return out_path


if __name__ == "__main__":
    main()
