#!/usr/bin/env python3
"""
extract_xray.py  --  AJ Bell ISA Portfolio X-Ray PDF parser
Version: 1.0  |  2026-05-31

Reads the latest AJ Bell ISA Portfolio X-Ray PDF from the ISA folder and produces
a clean xray_data_mmm_yyyy.json. Called by monthly_isa_prerun.py.

Usage (standalone):
    python3 extract_xray.py [--pdf /path/to/file.pdf] [--out /path/to/output.json]

Output: xray_data_mmm_yyyy.json with:
  - Asset allocation (stocks, bonds, cash, other)
  - Geographic/country exposure (vs benchmark)
  - World region breakdown (vs benchmark)
  - Stock sector weights (vs benchmark)
  - Investment style box
  - Trailing performance (3m, 6m, 1yr, 3yr, 5yr, YTD)
  - Per-fund holdings table (name, Morningstar rating, 1yr/3yr/5yr returns, weight %, TER)

PDF format: Morningstar Portfolio X-Ray as generated by AJ Bell.
Parsing uses a combination of pdfplumber text extraction and regex.
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime

import pdfplumber


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
ISA_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# Morningstar star rating — AJ Bell PDF uses "Q" for stars
MS_RATING_MAP = {"QQQQQ": 5, "QQQQ": 4, "QQQ": 3, "QQ": 2, "Q": 1}

# Known sector codes in X-Ray PDF
SECTOR_MAP = {
    "Basic Materials":       "basic_materials",
    "Communication Services":"communication_services",
    "Consumer Cyclical":     "consumer_cyclical",
    "Consumer Defensive":    "consumer_defensive",
    "Energy":                "energy",
    "Financial Services":    "financial_services",
    "Healthcare":            "healthcare",
    "Industrials":           "industrials",
    "Real Estate":           "real_estate",
    "Technology":            "technology",
    "Utilities":             "utilities",
}


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------
def find_latest_xray(folder: str) -> str:
    """Find latest AJ Bell ISA Portfolio X-Ray PDF (not 'End of Tax Year')."""
    pattern = os.path.join(folder, "AJ Bell ISA Portfolio X-Ray *.pdf")
    candidates = [
        f for f in glob.glob(pattern)
        if "end of tax year" not in os.path.basename(f).lower()
    ]
    if not candidates:
        raise FileNotFoundError(
            f"No AJ Bell ISA Portfolio X-Ray PDF found in: {folder}\n"
            f"Expected filename: 'AJ Bell ISA Portfolio X-Ray DD-Mmm-YY.pdf'"
        )

    def _parse_date(path):
        name = os.path.basename(path)
        m = re.search(r"(\d{2}-\w{3}-\d{2,4})\.pdf$", name, re.IGNORECASE)
        if m:
            for fmt in ("%d-%b-%y", "%d-%b-%Y"):
                try:
                    return datetime.strptime(m.group(1), fmt)
                except ValueError:
                    pass
        return datetime.min

    return max(candidates, key=_parse_date)


# ---------------------------------------------------------------------------
# Text extraction helpers
# ---------------------------------------------------------------------------
def extract_all_text(pdf_path: str) -> str:
    """Extract all text from PDF, one page at a time, joined with newlines."""
    pages = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            t = page.extract_text() or ""
            pages.append(t)
    return "\n\n".join(pages)


def safe_float(s: str) -> float | None:
    """Convert string to float, return None on failure."""
    if s is None:
        return None
    s = str(s).strip().replace(",", "").replace("%", "")
    if s in ("", "-", "—", "N/A", "n/a"):
        return None
    try:
        return float(s)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Parser sections
# ---------------------------------------------------------------------------
def parse_report_date(text: str) -> str:
    m = re.search(r"Report as of\s+(\d+\s+\w+\s+\d{4})", text)
    if m:
        try:
            dt = datetime.strptime(m.group(1), "%d %B %Y")
            return dt.strftime("%d-%b-%Y")
        except ValueError:
            return m.group(1)
    m2 = re.search(r"Date\s*:\s*(\w+\s+\d+\s+\d{4})", text)
    if m2:
        try:
            dt = datetime.strptime(m2.group(1), "%B %d %Y")
            return dt.strftime("%d-%b-%Y")
        except ValueError:
            return m2.group(1)
    return "unknown"


def parse_asset_allocation(text: str) -> dict:
    """Extract asset allocation percentages from X-Ray page 2 text."""
    result = {}
    # Pattern: "Stocks 90.31 0.05 90.26"
    for asset in ["Stocks", "Bonds", "Cash", "Other", "Not classified"]:
        m = re.search(
            rf"{re.escape(asset)}\s+([\d.]+)\s+([\d.]+)\s+([\-\d.]+)", text
        )
        if m:
            key = asset.lower().replace(" ", "_")
            result[key] = {
                "long_pct":  safe_float(m.group(1)),
                "short_pct": safe_float(m.group(2)),
                "net_pct":   safe_float(m.group(3)),
            }
    return result


# Fix Pack A10 (P2): STATIC country whitelist — the old catch-all [A-Z][a-z]+ arm ingested
# header/label rows as data ("June" 2026.0, "Benchmark" rows). Whitelist + 0-100 pct-range
# validation; rejected rows land in PARSE_WARNINGS (surfaced via _meta.parse_warnings and the
# pre-run schema assert). "Other"/"Others" is a legitimate residual row and is included.
COUNTRY_WHITELIST = frozenset([
    "United States", "United Kingdom", "Japan", "China", "France", "Taiwan",
    "Republic of Korea", "South Korea", "Spain", "Italy", "Germany", "Canada",
    "Australia", "Netherlands", "Switzerland", "Sweden", "Denmark", "Norway",
    "Finland", "India", "Brazil", "Hong Kong", "Singapore", "Mexico", "Belgium",
    "Austria", "Ireland", "Portugal", "Israel", "New Zealand", "South Africa",
    "Indonesia", "Malaysia", "Thailand", "Philippines", "Vietnam", "Poland",
    "Turkey", "Greece", "Chile", "Colombia", "Peru", "Argentina", "Saudi Arabia",
    "United Arab Emirates", "Qatar", "Kuwait", "Egypt", "Luxembourg", "Iceland",
    "Other", "Others",
])

PARSE_WARNINGS: list = []   # A10 — reset per extract run; copied into _meta.parse_warnings


def _valid_pct(v):
    return v is None or (isinstance(v, (int, float)) and 0.0 <= v <= 100.0)


def parse_country_exposure(text: str) -> list:
    """
    Extract country exposure table. Returns list of
    {country, equity_pct, benchmark_pct}.
    A10: whitelist countries; reject pct outside 0-100; rejected rows -> PARSE_WARNINGS.
    """
    countries = []
    # Lines like: "United States 40.03 65.85" (two side-by-side columns in PDF text)
    pattern = re.compile(
        r"([A-Z][A-Za-z]+(?:\s[A-Za-z][A-Za-z]+){0,3})"
        r"\s+([\d.]+)\s+([\d.]+)"
    )
    for m in pattern.finditer(text):
        name = m.group(1).strip()
        eq, bench = safe_float(m.group(2)), safe_float(m.group(3))
        if name not in COUNTRY_WHITELIST:
            # header/label/date rows are EXPECTED matches of the loose pattern — only warn on
            # rows that look plausibly geographic (both pcts in range) so the warning list
            # stays signal, not noise
            if _valid_pct(eq) and _valid_pct(bench) and eq is not None:
                PARSE_WARNINGS.append(f"country row rejected (not whitelisted): {name!r} {eq}/{bench}")
            continue
        if not (_valid_pct(eq) and _valid_pct(bench)):
            PARSE_WARNINGS.append(f"country row rejected (pct out of 0-100): {name!r} {eq}/{bench}")
            continue
        countries.append({
            "country":       name,
            "equity_pct":    eq,
            "benchmark_pct": bench,
        })
    # Deduplicate (PDF may repeat entries)
    seen = set()
    unique = []
    for c in countries:
        k = c["country"]
        if k not in seen:
            seen.add(k)
            unique.append(c)
    return unique


def parse_world_regions(text: str) -> dict:
    """Extract world region breakdown {region: {equity_pct, benchmark_pct}}."""
    regions = {}
    # Pattern: "Greater Europe 34.73 19.34"
    region_names = [
        "Greater Europe", "Americas", "Greater Asia",
        "United Kingdom", "Western Europe",
        "United States", "Canada",
        "Japan", "Australasia",
        "Emerging 4 Tigers", "Emerging Asia",
        "Emerging Europe", "Middle East / Africa",
        "Central & Latin America",
    ]
    for rn in region_names:
        m = re.search(
            rf"{re.escape(rn)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if m:
            key = rn.lower().replace(" ", "_").replace("/", "_").replace("&", "and")
            regions[key] = {
                "name":          rn,
                "equity_pct":    safe_float(m.group(1)),
                "benchmark_pct": safe_float(m.group(2)),
            }
    return regions


def parse_sector_weights(text: str) -> dict:
    """
    Extract stock sector weights vs benchmark.
    Returns {sector_key: {name, portfolio_pct, benchmark_pct}}.
    """
    sectors = {}
    # Pattern lines: "sConsumer 5.59 5.16" or "yFinancial 17.42 16.54"
    # The PDF prefixes each sector with a single letter icon — strip it.
    for sector_name, key in SECTOR_MAP.items():
        # Match the sector name (possibly with leading letter/icon) followed by two numbers
        m = re.search(
            rf".{{0,3}}{re.escape(sector_name)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if not m:
            # Try abbreviated name (first word only for communication services etc.)
            short = sector_name.split()[0]
            m = re.search(rf".{{0,3}}{re.escape(short)}\w*\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            sectors[key] = {
                "name":          sector_name,
                "portfolio_pct": safe_float(m.group(1)),
                "benchmark_pct": safe_float(m.group(2)),
                "vs_benchmark":  round(
                    (safe_float(m.group(1)) or 0) - (safe_float(m.group(2)) or 0), 2
                ),
            }
    return sectors


def parse_trailing_returns(text: str) -> dict:
    """
    Extract trailing returns table.
    Returns {period: {portfolio_pct, benchmark_pct, relative_pct}}.
    """
    returns = {}
    periods = {
        "3 Months":           "3m",
        "6 Months":           "6m",
        "1 Year":             "1yr",
        "3 Years Annualised": "3yr_ann",
        "5 Years Annualised": "5yr_ann",
        "YTD":                "ytd",
    }
    for label, key in periods.items():
        m = re.search(
            rf"{re.escape(label)}\s+([\d.]+)\s+([\d.]+)", text
        )
        if m:
            port  = safe_float(m.group(1))
            bench = safe_float(m.group(2))
            rel   = round((port or 0) - (bench or 0), 2) if port is not None and bench is not None else None
            returns[key] = {
                "period":        label,
                "portfolio_pct": port,
                "benchmark_pct": bench,
                "relative_pct":  rel,
            }
    return returns



_MONTHS = {m.lower(): i for i, m in enumerate(
    ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], 1)}


def _parse_fund_as_of(raw):
    """'30 Jun 2026' -> '2026-06-30'. D1: this date is the ONLY honest statement
    of when a per-fund return was struck, and it is routinely a month behind the
    report header. Returning None is fine -- the caller flags it -- but silently
    inheriting the header date is not."""
    if not raw:
        return None
    parts = raw.split()
    if len(parts) != 3:
        return None
    try:
        day = int(parts[0]); mon = _MONTHS.get(parts[1][:3].lower()); yr = int(parts[2])
        return f"{yr:04d}-{mon:02d}-{day:02d}" if mon else None
    except (ValueError, TypeError):
        return None


def stamp_fund_staleness(funds, report_date):
    """I4 -- every per-fund figure must declare how stale it is vs the report
    header. Returns (funds, warnings). A gap is NOT an error (Morningstar lags
    by design); publishing it undated IS."""
    import datetime as _dt
    warnings = []
    try:
        rep = _dt.date.fromisoformat((report_date or "")[:10])
    except (ValueError, TypeError):
        rep = None
    worst = 0
    for f in funds:
        if f.get("as_of") and rep:
            try:
                d = (rep - _dt.date.fromisoformat(f["as_of"])).days
            except ValueError:
                d = None
            f["stale_days"] = d
            f["as_of_basis"] = "per-fund Date column (NOT the report header)"
            if d and d > 5:
                worst = max(worst, d)
        else:
            f["stale_days"] = None
            f["as_of_basis"] = "UNKNOWN -- no per-fund date parsed"
            warnings.append(f"I4: '{f.get('name','?')}' has no per-fund as_of; "
                            "its returns must NOT be presented as current")
    if worst:
        warnings.append(
            f"I4: X-Ray per-fund performance is {worst} days older than the report "
            f"date {report_date}. These are CORROBORATORS only -- fund_performance.py "
            f"is the golden source. Render as 'x.xx% (as at <date>)', never bare.")
    return funds, warnings



def parse_holdings_statistics(text: str) -> dict:
    """Per-fund **Mean** and **Std Dev** from the `Portfolio Holdings Statistics` table.

    ⚑ NOT PARSED AT ALL BEFORE 05-Aug-2026, and it is the table register item H7 is built on
    ("RLGES 17.73/13.77 vs VUAG 18.01/13.37"). Without it the framework could quote H7 but not
    reproduce, re-test or refresh it.

    ⚑ AND ITS WINDOW IS UNSTATED. The columns are headed only `Name Assets Mean Std Dev` — no
    period. The window was identified as **3 YEARS** by reconciling the published std devs
    against NAV-derived figures (VUAG 13.37 vs a 3y 13.24-13.43 and a 5y 13.09; RLGES 13.77 vs
    a 3y 13.62 and a 5y 13.04; same conclusion on Ranmore and Thornbridge). It is recorded as
    `window_basis: "inferred_3y"` — inferred, and labelled as inferred, because a number whose
    period is assumed is exactly the semantic-drift class this framework keeps paying for.
    **This matters: the VUAG-vs-RLGES dominance verdict REVERSES between the 3y and 5y windows.**
    """
    out = {"funds": {}, "order": [], "by_index": {}, "missing_indices": [],
           "window_basis": "inferred_3y",
           "window_note": ("the source table states no period; 3 years identified by "
                           "reconciling published std devs against NAV-derived 3y and 5y "
                           "figures across four funds")}
    i = text.find("Portfolio Holdings Statistics")
    if i == -1:
        return out
    seg = text[i:i + 4000]
    # The RIGHT-HAND statistics panel bleeds onto the same physical line for several rows
    # ("... 11.75 18.01 13.37 Standard Deviation 12.99 12.75"), so anchoring at end-of-line
    # dropped 7 of 13 funds — including, again, VUAG.
    row = re.compile(r"^\s*(\d+)\s+([A-Za-z][A-Za-z0-9 &\-\.\'()\u00a3/]+?)\s+"
                     r"([\d.]+)\s+([\d.]+|-)\s+([\d.]+|-)(?:\s|$)", re.M)
    for m in row.finditer(seg):
        idx = int(m.group(1))
        name = m.group(2).strip()
        if len(name) < 4:
            continue
        out["funds"][name] = {
            "row_index": idx,
            "assets_pct": safe_float(m.group(3)),
            "mean": safe_float(m.group(4)),
            "std_dev": safe_float(m.group(5)),
        }
        out["by_index"][idx] = name
        out["order"].append(name)
    # ⚑ THE PRINTED ROW NUMBER IS THE KEY, NOT THE POSITION IN THIS LIST. The Correlation Matrix
    # is indexed against THESE row numbers and carries no fund names of its own. Row 6 is
    # "Cash GBP", whose lowercase letters the original all-caps name pattern rejected — so a
    # positional mapping silently closed the gap and shifted rows 7-10 up by one, handing Royal
    # London's 0.91 correlation with VUAG to MI Thornbridge. That single number is the entire
    # basis of register H7's fee argument. Any missing index is now RECORDED, and the correlation
    # mapping refuses the affected rows rather than sliding.
    seen = sorted(out["by_index"])
    if seen:
        out["missing_indices"] = [i for i in range(1, max(seen) + 1) if i not in out["by_index"]]
        if out["missing_indices"]:
            PARSE_WARNINGS.append(
                f"holdings_statistics: row indices {out['missing_indices']} did not parse "
                f"(typically the 'Cash GBP' row). Recorded, so the correlation matrix cannot "
                f"map across the gap.")
    return out


def parse_lookthrough_top10(text: str) -> dict:
    """H10 — the `Top 10 Underlying Holdings` table: portfolio-level LOOK-THROUGH exposure.

    ⚑ NEVER PARSED BEFORE (06-Aug-2026), and the framework was hand-computing the same numbers
    and getting them wrong. `portfolio_analytics.build_overlap_check_structure` asked Claude to
    look up each stock in each fund's top ten and add it to the direct weight by hand. On the
    August run that produced **AVGO 4.04%**, missing MI Thornbridge's 3.84% position. The X-Ray
    publishes the answer — **4.31%** — as a table, computed by Morningstar across the actual
    underlying holdings of every fund, which is a source the hand-calc could never match.

    A hand-computed figure that a machine-readable source already publishes is not a fallback,
    it is a second source of truth that will drift. Standard rule 5: one home per rule.

    ⚑ COVERAGE IS EXPLICIT. This is the top TEN only, so a name below the tenth is UNKNOWN, not
    zero. `covered_pct` is reported so the difference is impossible to overlook: on August data
    the ten names cover 18.12% of the portfolio and the other ~82% is simply not in this table.
    """
    out = {"holdings": [], "covered_pct": None, "source_table": "Top 10 Underlying Holdings",
           "coverage_note": ("TOP TEN ONLY. A name absent from this table is UNRANKED, not "
                             "absent from the portfolio — treating absence as zero exposure is "
                             "the single easiest way to under-read a concentration.")}
    i = text.find("Top 10 Underlying Holdings")
    if i == -1:
        PARSE_WARNINGS.append("lookthrough_top10: section header not found")
        return out
    seg = text[i:i + 2500]
    # "4.31 Broadcom Inc Stock Technology United States"
    # ⚑ SECTOR IS MATCHED AGAINST A CLOSED VOCABULARY, not "everything up to the last words".
    # A greedy split read "Communication Services United States" as sector "Communication" and
    # country "Services United States", and "Consumer Cyclical United States" the same way — two
    # of the ten rows silently mangled, in a table whose entire purpose is naming exposures.
    sectors = sorted(set(SECTOR_MAP.values()) | {
        "Technology", "Communication Services", "Financial Services", "Consumer Cyclical",
        "Consumer Defensive", "Healthcare", "Industrials", "Basic Materials", "Energy",
        "Utilities", "Real Estate"}, key=len, reverse=True)
    row = re.compile(r"^\s*(\d+\.\d+)\s+(.+?)\s+(Stock|Equity|Bond|Cash|Fund|Other)\s+"
                     r"(" + "|".join(re.escape(x) for x in sectors) + r")\s+"
                     r"([A-Z][A-Za-z .'\-]+?)\s*$", re.M)
    for m in row.finditer(seg):
        pct = safe_float(m.group(1))
        name = m.group(2).strip()
        if pct is None or not name or len(name) < 2:
            continue
        out["holdings"].append({
            "name": name, "weight_pct": pct, "security_type": m.group(3).strip(),
            "sector": m.group(4).strip(), "country": m.group(5).strip()})
        if len(out["holdings"]) == 10:
            break
    if out["holdings"]:
        out["covered_pct"] = round(sum(h["weight_pct"] for h in out["holdings"]), 2)
        # ⚑ a monotonicity check, because a mis-parsed row is far more likely to break the
        # ordering than to look plausible: the table is published in descending weight.
        w = [h["weight_pct"] for h in out["holdings"]]
        if w != sorted(w, reverse=True):
            PARSE_WARNINGS.append(
                f"lookthrough_top10: rows are NOT in descending weight order {w} — the parse "
                f"has picked up something that is not a holdings row")
            out["order_warning"] = w
    else:
        PARSE_WARNINGS.append("lookthrough_top10: header found but NO rows parsed")
    if len(out["holdings"]) not in (0, 10):
        PARSE_WARNINGS.append(
            f"lookthrough_top10: parsed {len(out['holdings'])} rows from a table titled TOP 10 — "
            f"a partial parse of a fixed-size table is a parser fault, not a short table")
    return out


def parse_correlation_matrix(text: str, stats_names=None) -> dict:
    """The `Correlation Matrix` — a SECOND, INDEPENDENT derivation of the fund-fund correlations
    `fund_action_stack` computes from monthly NAV returns.

    Standard rule 4 asks for two derivations that must agree, and this is the only other one
    available. It matters immediately: the RLGES-vs-VUAG fee argument in register H7 rests on a
    correlation of **0.91**, which until now was a number quoted from a PDF nobody had parsed.

    ⚑ THE ROW LABELS ARE NUMBERS, NOT NAMES. The matrix is indexed 1..10 and the mapping to funds
    lives in the SEPARATE `Top 10 Portfolio Holdings Statistics` table, which is numbered the same
    way. So this parser REQUIRES that table's ordered names to be handed in; without them it
    returns the numeric matrix and NO fund mapping rather than assuming the order. Guessing an
    index-to-fund mapping is exactly how a correlation gets attached to the wrong pair — the same
    wrong-fund join that produced a false DISPUTED verdict in August.
    """
    out = {"matrix": {}, "index_to_fund": {}, "pairs": {}, "window_basis": "inferred_3y",
           "window_note": ("the matrix is printed beside a 3-Yr Mean / 3-Yr Standard Deviation "
                           "scatter and states no period of its own; 3 years is inferred from "
                           "that adjacency and labelled as inferred")}
    i = text.find("Correlation Matrix")
    if i == -1:
        return out
    seg = text[i:i + 2500]
    # ⚑ THE MATRIX SHARES ITS LINES WITH A SCATTER PLOT. Extracted text interleaves axis labels
    # and point markers with the matrix rows — row 3 arrives as "46 3 0.43 0.80 1.00" and row 8 as
    # "3 10 8 0.83 0.57 0.66 0.61 0.73 - 0.85 1.00". Anchoring the index at line start found only
    # rows 1, 2, 4, 7 and 10 and reported the rest as absent. The index is therefore the LAST
    # integer before the run of decimals, and the parse is validated structurally rather than
    # positionally: row n of a lower-triangular matrix has exactly n entries and its last is its
    # own diagonal. A mis-parse cannot satisfy that.
    row = re.compile(r"(\d{1,2})\s+((?:(?:-?\d\.\d{2}|-)\s+)*(?:-?\d\.\d{2}|-))\s*$", re.M)
    rejected = []
    for m in row.finditer(seg):
        idx = int(m.group(1))
        vals = [None if v == "-" else float(v) for v in m.group(2).split()]
        if len(vals) != idx:
            rejected.append({"index": idx, "n_values": len(vals)})
            continue
        if vals[-1] is not None and abs(vals[-1] - 1.00) > 1e-9:
            rejected.append({"index": idx, "diagonal": vals[-1]})
            continue
        out["matrix"][idx] = vals
    out["rejected_rows"] = rejected
    if out["matrix"]:
        got = sorted(out["matrix"])
        out["missing_rows"] = [i for i in range(1, max(got) + 1) if i not in out["matrix"]]
    if stats_names:
        # `stats_names` is an INDEX->NAME map from the statistics table's printed row numbers.
        # A plain ordered list is refused: it is the shape that produced the off-by-one above.
        if not isinstance(stats_names, dict):
            out["mapping_note"] = ("refused: an ordered LIST was supplied. The mapping must be "
                                   "keyed on the table's printed row numbers, because a dropped "
                                   "row (Cash GBP) shifts every fund after it.")
            return out
        out["index_to_fund"] = {int(k): v for k, v in stats_names.items()}
        for idx, vals in out["matrix"].items():
            for j, v in enumerate(vals, start=1):
                if v is None or j >= idx:
                    continue
                a, b = out["index_to_fund"].get(idx), out["index_to_fund"].get(j)
                if a and b:
                    out["pairs"][f"{a} | {b}"] = v
    else:
        out["mapping_note"] = ("no ordered fund list supplied, so the numeric indices are NOT "
                               "mapped to funds. An assumed order would attach a correlation to "
                               "the wrong pair, which is worse than having none.")
    return out


def parse_fund_holdings(text: str) -> list:
    """
    Extract Portfolio Holdings table (page 4 of PDF).
    Returns list of fund dicts.
    """
    funds = []

    # Find the holdings section
    holdings_start = text.find("Portfolio Holdings\nName Type Holding")
    if holdings_start == -1:
        holdings_start = text.find("Portfolio Holdings")
    if holdings_start == -1:
        return funds

    section = text[holdings_start:]

    # Each fund line (approximate):
    # "FUND NAME Type Date MS_RATING 1yr 3yr 5yr weight% TER OC"
    # Use a flexible pattern
    # ⚑ FIXED 05-Aug-2026. The name class excluded DIGITS and the POUND SIGN, and the type
    # alternation could not match a three-part type. Two holdings were therefore dropped
    # silently on every run:
    #     VANGUARD S&P 500 ETF USD ACC GBP     name contains "500"; type is "Mutual Fund - ETF"
    #     VANGUARD JPN STK IDX £ ACC           name contains "£"
    # Between them that is **16.2% of the portfolio, including the single largest holding at
    # 11.62%**, invisible to every X-Ray-derived check — which is precisely why the dominance
    # test could not adjudicate VUAG and reported it as having no second source.
    # A parser that drops a row it cannot match, without counting it, produces a table that
    # looks complete and is not.
    fund_pattern = re.compile(
        r"([A-Z][A-Z0-9 &\-\.\'()\u00a3/]+?)\s+"   # Fund name (caps, digits, GBP sign)
        # ⚑ The type cell WRAPS. VUAG's row reads "... GBP Mutual 30 Jun 2026 QQQQ ..." with
        # "Fund -" and "ETF" on the two FOLLOWING lines, so the type token on the data line is
        # the bare word "Mutual". Requiring "Mutual Fund" contiguous is why the largest holding
        # was dropped.
        r"(?:Mutual\s+Fund|Mutual|Fund|ETF|Cash)\s*"
        r"(?:\s*-\s*)?(?:ETF)?\s*"                 # optional " - ETF" continuation
        r"(\d+ \w+ \d{4})?\s*"                  # D1 FIX: the per-fund AS-AT DATE.
                                                 # This was NON-capturing -- the date the
                                                 # figures are actually struck at was parsed
                                                 # and DISCARDED, so month-old returns were
                                                 # published under the report header date.
        r"(Q{1,5}|-)\s*"                         # MS Rating (Q's or dash)
        r"([\d.]+|-)\s+"                          # 1yr
        r"([\d.]+|-)?\s*"                        # 3yr
        r"([\d.]+|-)?\s*"                        # 5yr
        r"([\d.]+)\s*"                           # weight %
        r"(-)\s*"                                # TER (always - in AJ Bell)
        r"([\d.]+|-)",                           # Ongoing cost
        re.IGNORECASE
    )

    for m in fund_pattern.finditer(section):
        name = m.group(1).strip()
        if len(name) < 5 or name.upper().startswith("NAME"):
            continue
        as_at_raw = (m.group(2) or "").strip()
        ms_str = m.group(3).strip()
        ms_rating = MS_RATING_MAP.get(ms_str) if ms_str != "-" else None

        fund_rec = {
            "name":         name,
            "as_of":        _parse_fund_as_of(as_at_raw),
            "as_of_raw":    as_at_raw or None,
            "ms_rating":    ms_rating,
            "return_1yr":   safe_float(m.group(4)),
            "return_3yr":   safe_float(m.group(5)),
            "return_5yr":   safe_float(m.group(6)),
            "weight_pct":   safe_float(m.group(7)),
            "ongoing_cost": safe_float(m.group(9)),
        }
        funds.append(fund_rec)

    # Deduplicate by name
    seen = set()
    unique = []
    for f in funds:
        k = f["name"][:20]
        if k not in seen:
            seen.add(k)
            unique.append(f)

    return unique


def parse_investment_style(text: str) -> dict:
    """Extract style box summary metrics."""
    style = {}
    for metric, key in [
        ("Price/Book Ratio",    "price_book"),
        ("Price/Earnings",      "price_earnings"),
        ("Price/Cashflow",      "price_cashflow"),
    ]:
        m = re.search(rf"{re.escape(metric)}\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            style[key] = {
                "portfolio":  safe_float(m.group(1)),
                "benchmark":  safe_float(m.group(2)),
            }
    return style


def parse_rstat(text: str) -> dict:
    """Extract 3yr/5yr risk and return statistics."""
    rstat = {}
    for metric, key in [
        ("Standard Deviation",  "std_dev"),
        ("Arithmetic Mean",     "arithmetic_mean"),
        ("Sharpe Ratio",        "sharpe"),
        ("Alpha",               "alpha"),
        ("Beta",                "beta"),
        ("R-Squared",           "r_squared"),
        ("Information Ratio",   "info_ratio"),
        ("Tracking Error",      "tracking_error"),
    ]:
        m = re.search(rf"{re.escape(metric)}\s+([\d.]+)\s+([\d.]+)", text)
        if m:
            rstat[key] = {
                "metric":   metric,
                "3yr":      safe_float(m.group(1)),
                "5yr":      safe_float(m.group(2)),
            }
    return rstat


# ---------------------------------------------------------------------------
# Main parser
# ---------------------------------------------------------------------------
def parse_xray(pdf_path: str) -> dict:
    text = extract_all_text(pdf_path)

    report_date = parse_report_date(text)

    # Derive month label
    month_label = "unknown"
    try:
        dt = datetime.strptime(report_date, "%d-%b-%Y")
        month_label = dt.strftime("%b_%Y").lower()
    except ValueError:
        pass

    PARSE_WARNINGS.clear()   # A10 — per-run warning capture (parsers below append)
    result = {
        "_meta": {
            "source_file":    os.path.basename(pdf_path),
            "report_date":    report_date,
            "month_label":    month_label,
            "extracted_at":   datetime.now().strftime("%Y-%m-%d %H:%M"),
        },
        "asset_allocation": parse_asset_allocation(text),
        "country_exposure":  parse_country_exposure(text),
        "world_regions":     parse_world_regions(text),
        "sector_weights":    parse_sector_weights(text),
        "investment_style":  parse_investment_style(text),
        "trailing_returns":  parse_trailing_returns(text),
        "risk_statistics":   parse_rstat(text),
        "fund_holdings":     parse_fund_holdings(text),
        "holdings_statistics": parse_holdings_statistics(text),
        "lookthrough_top10": parse_lookthrough_top10(text),
    }
    result["correlation_matrix"] = parse_correlation_matrix(
        text, (result["holdings_statistics"] or {}).get("by_index"))
    result["_meta"]["parse_warnings"] = list(PARSE_WARNINGS)   # Fix Pack A10

    # Validation
    warnings = []
    if not result["sector_weights"]:
        warnings.append("sector_weights: no data extracted — check PDF format")
    if not result["trailing_returns"]:
        warnings.append("trailing_returns: no data extracted")
    if not result["fund_holdings"]:
        warnings.append("fund_holdings: no data extracted — check PDF format")
    if not (result.get("lookthrough_top10") or {}).get("holdings"):
        warnings.append("lookthrough_top10: no data extracted — the hand-calculated overlap it "
                        "replaces is WRONG (AVGO 4.04% vs the published 4.31%), so an absent "
                        "parse must be loud, not a quiet fallback")
    if warnings:
        result["_warnings"] = warnings

    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Extract AJ Bell ISA X-Ray PDF to structured JSON."
    )
    parser.add_argument("--pdf", default=None,
                        help="Path to X-Ray PDF. Auto-detects latest if omitted.")
    parser.add_argument("--out", default=None,
                        help="Output JSON path. Defaults to xray_data_mmm_yyyy.json.")
    parser.add_argument("--isa-folder", default=ISA_FOLDER)
    args = parser.parse_args()

    if args.pdf:
        pdf_path = args.pdf
        if not os.path.exists(pdf_path):
            print(f"ERROR: PDF not found: {pdf_path}")
            sys.exit(1)
    else:
        try:
            pdf_path = find_latest_xray(args.isa_folder)
        except FileNotFoundError as e:
            print(f"ERROR: {e}")
            sys.exit(1)
        print(f"Auto-detected: {os.path.basename(pdf_path)}")

    print(f"Parsing: {pdf_path}")
    try:
        data = parse_xray(pdf_path)
    except Exception as e:
        print(f"ERROR parsing X-Ray PDF: {e}")
        sys.exit(1)

    # Output
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if args.out:
        out_path = args.out
    else:
        month_label = data["_meta"]["month_label"]
        out_path = os.path.join(script_dir, f"xray_data_{month_label}.json")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    # Summary
    print(f"\nX-Ray extracted: {data['_meta']['report_date']}")
    sw = data.get("sector_weights", {})
    print(f"  Sectors extracted:  {len(sw)}")
    tr = data.get("trailing_returns", {})
    if "1yr" in tr:
        r = tr["1yr"]
        print(f"  1yr return:         {r.get('portfolio_pct','?')}% portfolio vs {r.get('benchmark_pct','?')}% benchmark")
    fh = data.get("fund_holdings", [])
    print(f"  Fund holdings rows: {len(fh)}")
    if data.get("_warnings"):
        print(f"\n  WARNINGS:")
        for w in data["_warnings"]:
            print(f"    - {w}")
    print(f"\nOutput written: {out_path}")
    return out_path


if __name__ == "__main__":
    main()
