"""P2 - migrate the legacy markdown registers into the canonical item store.

Standard: ISA_Engineering_Rules.md (referenced by rule id, never restated).
Spec:     ISA_BuildSpec_ItemRegister_4C_09Aug2026.md  s6 (migration), s9 (P2).

WHAT THIS IS
------------
Three markdown registers held the framework's open work. The moment a second register
exists, one of them starts lying (ISA-0025). This module moves them into
Dashboard/state/isa_items.jsonl and leaves them as renders.

THE DISCIPLINE, AND WHY IT IS THE WHOLE DESIGN
----------------------------------------------
Spec s6.3(a): migration is MECHANICAL EXTRACTION PLUS EXPLICIT MISSING, never
interpretation. A one-pass reading of 1,500 lines of narrative is exactly the
plausible-but-wrong artefact this register exists to catch.

So:
  * every item-shaped row and heading in the three sources is EXTRACTED (never
    hand-typed), with its verbatim text carried into `narrative`;
  * every extracted candidate must be resolved by a DECLARATION - MIGRATE, ALIAS
    (already in the store) or EXCLUDE (with a reason). An unresolved candidate
    RAISES (R4.9: a reader that cannot match a row counts it and fails);
  * the declaration states how many occurrences it expects. A source edit that adds
    or removes an occurrence FAILS the migration rather than silently re-reading it
    (R5.2 - two independent derivations of the same fact must agree);
  * fields the text does not literally yield are left absent, never inferred
    (R7.5, R4.1). `provenance` is `backfilled` on every migrated record and trend
    metrics start Sep-2026.

COLLISIONS ARE THE POINT
------------------------
The sources carry four unrelated `D-` schemes and two different `D1`s in ONE file
(X-Ray staleness at line 484, Artemis SmartGARP at line 1167). Legacy ids are
therefore NEVER used as store ids; each maps through isa_id_map.json qualified by
source (R7.6). A declaration whose id denotes more than one item declares each
definition line explicitly, so a merge cannot happen by accident.

CLI:
  python3 isa_register_migrate.py --extract          # candidate report, writes nothing
  python3 isa_register_migrate.py --plan             # resolve against declarations
  python3 isa_register_migrate.py --apply            # write to the store
  python3 isa_register_migrate.py --reconcile        # P2 gate (spec s9)
  python3 isa_register_migrate.py --selftest

Stdlib only. Imports isa_register (the only writer) and NO Dashboard module.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import isa_register as R

MIGRATION_VERSION = "1.0.0"
DECLARATIONS_FILE = "isa_migration_declarations.json"
MANIFEST_FILE = "isa_migration_manifest.json"

SOURCE_FILES = {
    "OPEN_ITEMS": "ISA_OPEN_ITEMS_REGISTER.md",
    "DECISION": "ISA_Decision_Register.md",
    "BACKLOG": "ISA_Build_Backlog_Ranked_08Aug2026.md",
}

# An id is 1-3 capitals, an optional hyphen, 1-2 digits, an optional lower-case
# suffix (Q1a, Q3b). Deliberately tight: a loose pattern turns prose into items.
_ID = r"[A-Z]{1,3}-?\d{1,2}[a-z]?"
_HEADING = re.compile(rf"^(?P<hashes>#{{2,5}})\s+(?:[⚑✅\s])*(?:~~)?\*{{0,2}}(?P<id>{_ID})\*{{0,2}}(?:~~)?(?=[.\s—:|]|$)")
_CELL_ID = re.compile(rf"^[⚑✅*~\s]*(?P<id>{_ID})\b")
_NUM_CELL = re.compile(r"^\s*(?P<n>\d{1,3})\s*$")

CRIT_FROM_SECTION = {"CRITICAL": "CRITICAL", "HIGH": "HIGH", "MEDIUM": "MEDIUM", "LOW": "LOW"}
VALID_CRIT = set(CRIT_FROM_SECTION)
VALID_SIZE = {"XS", "S", "M", "L", "XL"}


ARCHIVE_DIR = "register_archive"
ARCHIVE_STEM = {"OPEN_ITEMS": "ISA_OPEN_ITEMS_REGISTER",
                "DECISION": "ISA_Decision_Register",
                "BACKLOG": "ISA_Build_Backlog_Ranked"}
GENERATED_MARK = "<!-- GENERATED BY isa_register_render.py - DO NOT EDIT (R14.3) -->"


def root_dir(root=None) -> Path:
    return Path(root).resolve() if root else Path(__file__).resolve().parent


def source_path(source: str, root=None) -> Path:
    """Resolve a legacy source, live or archived.

    Once P2 lands, the live paths hold GENERATED renders and the hand-written originals live
    in register_archive/. The migration must stay RE-RUNNABLE after that, because the
    reconciliation gate is the liveness reference that closes the item (R7.3) - a gate that
    can only ever run once is not a check, it is an anecdote. So: use the live file while it
    is still the original, and fall back to the archived original the moment it is not.
    """
    d = root_dir(root)
    live = d / SOURCE_FILES[source]
    if live.exists() and GENERATED_MARK not in live.read_text(encoding="utf-8")[:400]:
        return live
    candidates = sorted((d / ARCHIVE_DIR).glob(f"{ARCHIVE_STEM[source]}_pre_P2_*.md"))
    if candidates:
        return candidates[-1]
    if live.exists():
        raise FileNotFoundError(
            f"{live.name} is a generated render and no archived original was found in "
            f"{d / ARCHIVE_DIR}. The migration cannot be re-derived and the P2 gate cannot run.")
    raise FileNotFoundError(f"migration source absent: {live}")


# ---------------------------------------------------------------- extraction

def _section_update(line: str, section: str):
    """Return (occurrence_id_or_None, new_section) for a heading line.

    ONE HOME (R4.4). extract() and header_map() previously tracked sections by two slightly
    different rules; the copy in header_map lost the ranked backlog's per-tier header rows,
    so every Size column read there silently returned None. Two copies of one rule, drifting.
    """
    m = _HEADING.match(line)
    if not m:
        return None, line.strip()
    # A level-1/2 heading that also names an id (the backlog's `## P0 - ...` tiers) is BOTH
    # an occurrence and the section for what follows.
    if len(m.group("hashes")) <= 2:
        return m.group("id"), line.strip()
    return m.group("id"), section


@dataclass
class Occurrence:
    source: str
    legacy_id: str
    line_no: int
    kind: str          # "heading" | "table_row"
    section: str
    raw: str
    cells: list = field(default_factory=list)


def _split_row(line: str) -> list:
    inner = line.strip()
    if inner.startswith("|"):
        inner = inner[1:]
    if inner.endswith("|"):
        inner = inner[:-1]
    return [c.strip() for c in inner.split("|")]


def extract(source: str, root=None) -> list:
    """Every item-shaped heading and table row, in document order.

    Table rows are matched on the FIRST CELL ONLY. Matching anywhere in the row
    would turn every prose reference to H7 into an occurrence of H7 - the silent
    over-match that mirrors the silent under-match R4.9 exists to stop.
    """
    path = source_path(source, root)
    out, section = [], ""
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if line.startswith("#"):
            item_id, section = _section_update(line, section)
            if item_id:
                out.append(Occurrence(source, item_id, n, "heading", section, line))
            continue
        if line.lstrip().startswith("|"):
            cells = _split_row(line)
            if not cells:
                continue
            if set(cells[0]) <= set("-: ") and cells[0]:
                continue  # markdown separator row
            m = _CELL_ID.match(cells[0])
            if m:
                out.append(Occurrence(source, m.group("id"), n, "table_row", section, line, cells))
            elif _NUM_CELL.match(cells[0]) and source == "BACKLOG":
                # The backlog numbers its items instead of naming them. A synthetic id
                # keyed to the number is still MECHANICAL - it is read off the row.
                num = _NUM_CELL.match(cells[0]).group("n")
                out.append(Occurrence(source, f"BL-{num}", n, "table_row", section, line, cells))
    return out


@dataclass
class Group:
    source: str
    legacy_id: str
    occurrences: list
    section: str
    first_line: int

    @property
    def key(self) -> str:
        return f"{self.source}:{self.legacy_id}"


def group_occurrences(occs: list) -> dict:
    groups = {}
    for o in occs:
        k = f"{o.source}:{o.legacy_id}"
        if k not in groups:
            groups[k] = Group(o.source, o.legacy_id, [], o.section, o.line_no)
        groups[k].occurrences.append(o)
    return groups


# ---------------------------------------------------------------- narrative + field reads

def _body_after_heading(lines: list, idx: int) -> str:
    """Heading text plus its body, to the next heading of the same or higher level."""
    head = lines[idx]
    level = len(head) - len(head.lstrip("#"))
    body = [head]
    for ln in lines[idx + 1:]:
        if ln.startswith("#"):
            lv = len(ln) - len(ln.lstrip("#"))
            if lv <= level:
                break
        body.append(ln)
    return "\n".join(body).rstrip()


def narrative_for(group: Group, root=None) -> str:
    """Verbatim source text. Spec s10: the prose is the most valuable content in the
    existing register and is preserved, never paraphrased."""
    lines = source_path(group.source, root).read_text(encoding="utf-8").splitlines()
    parts = []
    for o in group.occurrences:
        if o.kind == "heading":
            parts.append(_body_after_heading(lines, o.line_no - 1))
        else:
            parts.append(o.raw.strip())
    return ("\n\n".join(parts)).strip()


def _column(group: Group, header_row_cells, wanted: str):
    """Read a named column off the FIRST table occurrence, by matching the header row.

    Reading by position would break the day a column is inserted, and would do so
    silently - which is the failure class this whole register exists to catch.
    """
    for o in group.occurrences:
        if o.kind != "table_row" or not o.cells:
            continue
        hdr = header_row_cells.get((o.source, o.section))
        if not hdr:
            continue
        for i, h in enumerate(hdr):
            if h.strip().lower() == wanted.lower() and i < len(o.cells):
                return o.cells[i].strip()
    return None


def header_map(root=None) -> dict:
    """(source, section) -> header cells, so columns are read by NAME (R4.2 spirit)."""
    out = {}
    for src, fname in SOURCE_FILES.items():
        section, pending = "", None
        for line in source_path(src, root).read_text(encoding="utf-8").splitlines():
            if line.startswith("#"):
                _, section = _section_update(line, section)
                pending = None
                continue
            if line.lstrip().startswith("|"):
                cells = _split_row(line)
                if cells and set(cells[0]) <= set("-: ") and cells[0]:
                    if pending is not None:
                        out.setdefault((src, section), pending)
                    pending = None
                else:
                    pending = cells
            else:
                pending = None
    return out


def _strip_md(text: str) -> str:
    text = re.sub(r"`([^`]*)`", r"\1", text or "")
    text = re.sub(r"\*{1,2}|~~|⚑", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _title_from(group: Group, hdrs, occ_first) -> str:
    """Title states the defect, not the fix (spec s4.1). Read from the row's own
    subject column, or from the heading text."""
    for col in ("Problem", "Finding", "Item", "What can be learned", "Requirement", "Outcome"):
        v = _column(group, hdrs, col)
        if v:
            return _strip_md(v)
    if occ_first.kind == "heading":
        t = re.sub(r"^#+\s*", "", occ_first.raw)
        t = re.sub(rf"^[⚑✅\s]*(?:~~)?\*{{0,2}}{re.escape(group.legacy_id)}\*{{0,2}}(?:~~)?[.\s—:]*", "", t)
        return _strip_md(t)
    if occ_first.cells and len(occ_first.cells) > 1:
        return _strip_md(occ_first.cells[1])
    return ""


def _crit_from_section(section: str):
    up = (section or "").upper()
    for word, val in CRIT_FROM_SECTION.items():
        if re.search(rf"\b{word}\b", up):
            return val
    return None


# ---------------------------------------------------------------- declarations

def declarations_path(root=None) -> Path:
    return R.store_dir() / DECLARATIONS_FILE if root is None else Path(root) / DECLARATIONS_FILE


def load_declarations(path=None) -> dict:
    p = Path(path) if path else (R.store_dir() / DECLARATIONS_FILE)
    if not p.exists():
        raise FileNotFoundError(
            f"{p} absent. Migration is declaration-driven by design: without it every "
            "classification would be an inference (spec s6.3a).")
    return json.loads(p.read_text(encoding="utf-8"))


VALID_DISPOSITIONS = {"MIGRATE", "ALIAS", "EXCLUDE"}


def plan(root=None, decl_path=None) -> dict:
    """Resolve every extracted candidate. RAISES on anything unresolved (R4.9)."""
    decls = load_declarations(decl_path)
    entries = decls["entries"]
    hdrs = header_map(root)

    groups = {}
    for src in SOURCE_FILES:
        groups.update(group_occurrences(extract(src, root)))

    unresolved, count_mismatch, orphan_decls = [], [], []
    to_migrate, aliases, excluded = [], [], []

    for key, g in sorted(groups.items(), key=lambda kv: (kv[1].source, kv[1].first_line)):
        d = entries.get(key)
        if d is None:
            unresolved.append(f"{key} (first at line {g.first_line}, section {g.section[:60]!r})")
            continue
        if d.get("disposition") not in VALID_DISPOSITIONS:
            unresolved.append(f"{key}: disposition {d.get('disposition')!r} is not one of {sorted(VALID_DISPOSITIONS)}")
            continue
        exp = d.get("occurrences_expected")
        if exp is None:
            unresolved.append(f"{key}: occurrences_expected absent - the count is the integrity check (R5.2)")
            continue
        if exp != len(g.occurrences):
            count_mismatch.append(
                f"{key}: declaration expects {exp} occurrence(s), the document has "
                f"{len(g.occurrences)} at lines {[o.line_no for o in g.occurrences]}")
            continue
        if d["disposition"] == "EXCLUDE":
            if not d.get("reason"):
                unresolved.append(f"{key}: EXCLUDE without a reason - silence is not a decision (R4.6)")
                continue
            excluded.append({"key": key, "reason": d["reason"], "lines": [o.line_no for o in g.occurrences]})
            continue
        if d["disposition"] == "ALIAS":
            if not d.get("canonical"):
                unresolved.append(f"{key}: ALIAS without a canonical id")
                continue
            aliases.append({"key": key, "legacy_id": g.legacy_id, "source": g.source,
                            "canonical": d["canonical"], "basis": d.get("basis", ""),
                            "lines": [o.line_no for o in g.occurrences]})
            continue
        to_migrate.append(_build_record(g, d, hdrs, root))

    for key in entries:
        if key not in groups:
            orphan_decls.append(key)

    problems = []
    if unresolved:
        problems.append("UNRESOLVED candidates (every extracted item must be declared - R4.9):\n  - "
                        + "\n  - ".join(unresolved))
    if count_mismatch:
        problems.append("OCCURRENCE COUNT DISAGREEMENT (the document and the declaration are two "
                        "derivations of one fact and they must agree - R5.2):\n  - "
                        + "\n  - ".join(count_mismatch))
    if orphan_decls:
        problems.append("DECLARATIONS with no candidate in the sources (a stale declaration is the "
                        "same defect as a stale register):\n  - " + "\n  - ".join(sorted(orphan_decls)))
    if problems:
        raise ValueError("migration plan refused:\n\n" + "\n\n".join(problems))

    return {"to_migrate": to_migrate, "aliases": aliases, "excluded": excluded,
            "groups": len(groups), "declarations": len(entries)}


def _build_record(g: Group, d: dict, hdrs, root) -> dict:
    """Mechanical extraction first; declared fields second; nothing inferred."""
    first = g.occurrences[0]

    crit_cell = _column(g, hdrs, "Crit")
    crit = None
    if crit_cell:
        c = _strip_md(crit_cell).upper()
        if c in VALID_CRIT:
            crit = c
    if crit is None:
        crit = _crit_from_section(g.section)
    crit_basis = "Crit column" if crit_cell else ("section heading" if crit else None)
    if crit is None:
        crit = d.get("criticality")
        crit_basis = "declared"
    if crit is None:
        raise ValueError(f"{g.key}: criticality is neither in the source nor declared (R4.1)")

    size_cell = _column(g, hdrs, "Size")
    size = None
    if size_cell:
        s = _strip_md(size_cell).upper().split("/")[0].split("–")[0].strip()
        if s in VALID_SIZE:
            size = s
    if size is None:
        size = d.get("size_est")

    title = d.get("title") or _title_from(g, hdrs, first)
    if len(title) < 5:
        raise ValueError(f"{g.key}: no title could be read from the source and none declared")
    title = f"[{g.legacy_id}] {title}"[:300]

    rec = {
        # NO id here. plan() is read-only and next_id() persists a high-water mark, so
        # allocating during planning burned 86 ids on every --plan and every --reconcile.
        # apply() assigns the id at the moment it writes. (ISA-0225.)
        "title": title,
        "aliases": [g.legacy_id, g.key],
        "record_type": d["record_type"],
        "state": d["state"],
        "criticality": crit,
        "size_est": size,
        "provenance": "backfilled",
        "narrative": narrative_for(g, root),
        "source_doc": f"{SOURCE_FILES[g.source]} line {first.line_no} (as_of {d.get('source_as_of', '2026-08-12')})",
        "intake_trigger": d.get("intake_trigger", "retrospective"),
        "detected_by": d.get("detected_by"),
        "detected_on": d.get("detected_on"),
        "introduced_basis": "unknown",
        "learning": d.get("learning") or {
            "learnable": False,
            "reason_none": "migrated record - L-0 was not asked at the time; not invented retrospectively (R7.5)"},
    }
    if d.get("is_fix") is not None:
        rec["is_fix"] = d["is_fix"]
    for k in ("domain", "failure_class", "blocked_question", "deferred_until", "deferred_reason",
              "evidence_basis", "evidence_note", "falsified_by", "revisit_by", "claim_status",
              "capital_link", "correction_subtype", "wontfix_accepted_by", "corrective_action",
              "cause_systemic", "resolved_on", "superseded_by", "verification", "blocks_run",
              "irreversible", "capital_impact", "standard_refs", "context"):
        if d.get(k) is not None:
            rec[k] = d[k]

    rec["_migration_basis"] = {
        "criticality": crit_basis,
        "size": "Size column" if size_cell else "declared/absent",
        "declaration_basis": d.get("basis", "not stated"),
        "source_line": first.line_no,
    }
    return rec


# ---------------------------------------------------------------- apply

def apply(root=None, decl_path=None, dry_run=True) -> dict:
    p = plan(root, decl_path)
    written, alias_rows = [], []

    existing_aliases = set()
    for it in R.read_all():
        for a in it.get("aliases", []):
            existing_aliases.add(a)

    for rec in p["to_migrate"]:
        basis = rec.pop("_migration_basis", None)
        if rec["aliases"][1] in existing_aliases:
            continue  # idempotent: already migrated under the same source-qualified key
        rec["id"] = R.next_id() if not dry_run else "ISA-DRYRUN"
        if not dry_run:
            R.write(rec)
            for legacy in rec["aliases"]:
                R.register_alias(legacy, rec["id"], source="P2_migration")
        written.append({"id": rec["id"], "aliases": rec["aliases"], "title": rec["title"],
                        "state": rec["state"], "criticality": rec["criticality"], "basis": basis})

    for a in p["aliases"]:
        if not dry_run:
            R.register_alias(a["key"], a["canonical"], source="P2_migration")
        alias_rows.append(a)

    manifest = {
        "migration_version": MIGRATION_VERSION,
        "as_of": R._today(),
        "dry_run": dry_run,
        "candidates_grouped": p["groups"],
        "declarations": p["declarations"],
        "migrated": len(written),
        "aliased_to_existing": len(alias_rows),
        "excluded": len(p["excluded"]),
        "records": written,
        "aliases": alias_rows,
        "exclusions": p["excluded"],
    }
    if not dry_run:
        (R.store_dir() / MANIFEST_FILE).write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest


# ---------------------------------------------------------------- the 4Cs (ISA-0226)
# Raj, 12-Aug-2026: "is there not 4 Cs for live items? i have seen some context in the files but
# not the other 3Cs." Measured: 73 of 73 migrated live items carried none of them.
#
# ⚑ I had conflated two different rules. R7.5 forbids INVENTING the 4Cs for historical items -
# correctly. It does not forbid EXTRACTING them where the source states them in a NAMED COLUMN.
# ISA_Decision_Register.md's approved table is literally `Problem | Decision | Justification`;
# the VCI table is `Finding | Note`; the learning table is
# `What can be learned | From data already held`. Those ARE the Cs, written down at the time.
#
# What is extracted is stamped with the column it came from. What is not in the source stays
# ABSENT-with-a-reason rather than absent-in-silence, so the gap is countable instead of
# invisible - the null-vs-missing class, in the register built to catch it.

FOURC_COLUMN_MAP = {
    # (source, section fragment): {register field: source column}
    ("DECISION", "APPROVED"): {"cause_proximate": "Problem",
                               "corrective_action": "Decision",
                               "consequence": "Justification"},
    ("DECISION", "OPEN"): {"cause_proximate": "Problem", "consequence": "Note"},
    ("DECISION", "VCI RUN"): {"cause_proximate": "Finding", "consequence": "Note"},
    ("DECISION", "CLOSED"): {"consequence": "Outcome"},
    ("DECISION", "LEARNING"): {"cause_proximate": "What can be learned",
                               "consequence": "From data already held"},
    ("OPEN_ITEMS", "HIGH"): {"cause_proximate": "Item", "consequence": "Detail"},
    ("OPEN_ITEMS", "MEDIUM"): {"cause_proximate": "Item", "consequence": "Detail"},
    ("OPEN_ITEMS", "QUANT-GRADE"): {"cause_proximate": "Requirement",
                                    "consequence": "Status 03-Aug"},
    ("BACKLOG", "P0"): {"cause_proximate": "Item", "consequence": "Why it is here"},
    ("BACKLOG", "P1"): {"cause_proximate": "Item", "consequence": "Note"},
    ("BACKLOG", "P2"): {"cause_proximate": "Item", "consequence": "Note"},
    ("BACKLOG", "P3"): {"cause_proximate": "Item", "consequence": "Note"},
}

# ONE HOME (R4.4): the marker and the field list live in isa_register, applied at write time.
NOT_RECORDED = R.NOT_RECORDED
FOURC_FIELDS = R.FOURC_FIELDS


def _columns_for(source: str, section: str):
    for (src, frag), mapping in FOURC_COLUMN_MAP.items():
        if src == source and frag.lower() in (section or "").lower():
            return mapping
    return None


def extract_4cs(root=None, decl_path=None, dry_run=False) -> dict:
    """Fill the 4Cs on migrated items from their own named source columns.

    Never invents. `cause_systemic` is deliberately left NOT RECORDED on every migrated item:
    it is genuinely absent from the sources, and manufacturing it is exactly what R7.5 forbids.
    """
    decls = load_declarations(decl_path)["entries"]
    hdrs = header_map(root)
    groups = {}
    for src in SOURCE_FILES:
        groups.update(group_occurrences(extract(src, root)))

    by_alias = {a: it for it in R.read_all() for a in it.get("aliases", [])}
    filled, absent = [], []
    for key, g in groups.items():
        d = decls.get(key)
        if not d or d.get("disposition") != "MIGRATE":
            continue
        item = by_alias.get(key)
        if item is None:
            continue
        mapping = _columns_for(g.source, g.section)
        new = dict(item)
        changed = False
        for field, column in (mapping or {}).items():
            if new.get(field):
                continue
            val = _column(g, hdrs, column)
            if val:
                text = _strip_md(val)
                if len(text) > 4:
                    new[field] = f"{text}  [extracted verbatim from the '{column}' column of "\
                                 f"{SOURCE_FILES[g.source]}]"
                    changed = True
        for field in FOURC_FIELDS:
            if field == "consequence_quantified":
                continue
            if not new.get(field):
                new[field] = NOT_RECORDED
                changed = True
                absent.append(f"{item['id']}:{field}")
        if changed:
            filled.append(item["id"])
            if not dry_run:
                R.write(new, allow_update=True)
    return {"items_filled": len(filled), "fields_marked_absent": len(absent), "dry_run": dry_run}


def fourc_status(items=None) -> dict:
    """Completeness per C, split by how it got there. Published in the rendered view."""
    items = items if items is not None else R.read_all()
    live = [i for i in items if i["state"] not in R.CLOSED_STATES]
    out = {}
    for f in FOURC_FIELDS:
        stated = sum(1 for i in live if i.get(f) and i.get(f) != NOT_RECORDED)
        declared_absent = sum(1 for i in live if i.get(f) == NOT_RECORDED)
        out[f] = {"stated": stated, "declared_absent": declared_absent,
                  "silently_absent": len(live) - stated - declared_absent}
    out["_live"] = len(live)
    return out

# ---------------------------------------------------------------- P2 gate (spec s9)

def reconcile(root=None, decl_path=None) -> dict:
    """THE P2 GATE: 'render matches the current register's open set, item for item.'

    Two independent derivations of one set (R5.2):
      A. the SOURCES, read fresh and filtered to declarations that say the item is open;
      B. the STORE, filtered to live states.
    A legacy id in one and not the other fails. A blended 'looks about right' count
    would conceal exactly the disagreement this gate exists to surface (R6.2).
    """
    decls = load_declarations(decl_path)
    entries = decls["entries"]
    groups = {}
    for src in SOURCE_FILES:
        groups.update(group_occurrences(extract(src, root)))

    live_states = {"OPEN", "IN_PROGRESS", "BLOCKED_ON_RAJ", "DEFERRED"}

    from_sources = set()
    for key, g in groups.items():
        d = entries.get(key)
        if d and d.get("disposition") == "MIGRATE" and d.get("state") in live_states:
            from_sources.add(key)

    from_store, closed_in_store = set(), set()
    for it in R.read_all():
        for a in it.get("aliases", []):
            # Only aliases from the THREE MIGRATION SOURCES belong in this comparison.
            # It originally matched any alias containing ':', which swept in the RETRO:
            # and RETROHASH: namespaces the moment retrospective intake shipped and failed
            # the gate on 100 items that were never in scope. A membership test that means
            # "looks like one of ours" is not a membership test (ISA-0232).
            if a.split(":", 1)[0] not in SOURCE_FILES:
                continue
            if it["state"] in live_states:
                from_store.add(a)
            else:
                closed_in_store.add(a)

    # ⚑ CLOSURE SINCE MIGRATION IS NOT A GATE FAILURE (ISA-0318, 12-Aug-2026).
    # `from_sources` is derived from the FROZEN declarations file, which records each item's state
    # AS AT MIGRATION. An item migrated as OPEN therefore stays "open in source" forever, so this
    # gate as first written could not survive the first legitimate closure of a migrated item -
    # and it duly failed the battery the moment D-2/D-3/D-4/D-23 were closed. That is the gate
    # being wrong, not the closure.
    #
    # ⚑ AND THE HOLE THIS DOES NOT OPEN. The exemption requires the alias to be PRESENT in the
    # store in a closed state. An alias absent from the store ENTIRELY is still a failure, which is
    # exactly what the dropped-item negative control produces. "Closed" and "missing" must never
    # converge on the same verdict - the same distinction the FRS return-adequacy fix rests on.
    missing_entirely = sorted(from_sources - from_store - closed_in_store)
    closed_since = sorted(from_sources & closed_in_store)
    extra = sorted(from_store - from_sources)
    return {"source_open": len(from_sources), "store_open": len(from_store),
            "in_source_not_store": missing_entirely,
            "closed_since_migration": closed_since,
            "in_store_not_source": extra,
            "reconciled": not missing_entirely and not extra,
            "reconciliation_basis": ("a migrated item that has since been CLOSED is reconciled and "
                                     "listed under closed_since_migration; an alias absent from the "
                                     "store altogether is NOT reconciled")}


# ---------------------------------------------------------------- selftest

def selftest(verbose=True, root=None) -> int:
    n = 0

    def ok(cond, msg):
        nonlocal n
        n += 1
        if not cond:
            raise AssertionError(msg)

    import tempfile
    tmp = Path(tempfile.mkdtemp(prefix="isa_mig_"))

    # --- extraction shape, on a fixture with every trap the real sources contain
    fixture = tmp / SOURCE_FILES["DECISION"]
    fixture.write_text(
        "# T\n\n## APPROVED — awaiting build\n\n"
        "| ID | Problem | Crit | Size |\n|---|---|---|---|\n"
        "| D-2 | A problem statement | HIGH | S |\n"
        "| ~~D-1~~ **DONE (ISA-0017)** | Struck through | HIGH | XS |\n"
        "\n## HIGH — open\n\n### H5. A heading item\nbody line one\nbody line two\n\n"
        "### Not an item heading\nprose that mentions H5 and D-2 in passing\n",
        encoding="utf-8")
    (tmp / SOURCE_FILES["OPEN_ITEMS"]).write_text("# empty\n", encoding="utf-8")
    (tmp / SOURCE_FILES["BACKLOG"]).write_text("# empty\n", encoding="utf-8")

    # --- source resolution falls back to the archived original once the live path is a render
    occ = extract("DECISION", tmp)
    ids = [o.legacy_id for o in occ]
    ok(ids == ["D-2", "D-1", "H5"], f"extraction order/content wrong: {ids}")
    ok(occ[1].legacy_id == "D-1", "a struck-through id must still be extracted, never skipped")
    ok(sum(1 for o in occ if o.legacy_id == "H5") == 1,
       "a prose MENTION of an id must not become an occurrence (over-match control)")

    hdrs = header_map(tmp)
    g = group_occurrences(occ)
    ok(_column(g["DECISION:D-2"], hdrs, "Crit") == "HIGH", "columns are read by NAME, not position")
    ok(_column(g["DECISION:D-2"], hdrs, "Size") == "S", "Size column read by name")
    nar = narrative_for(g["DECISION:H5"], tmp)
    ok("body line two" in nar and "Not an item heading" not in nar,
       "heading narrative runs to the next same-level heading and no further")

    # --- declaration gate: unresolved candidate must RAISE (R4.9)
    dpath = tmp / DECLARATIONS_FILE
    dpath.write_text(json.dumps({"entries": {}}), encoding="utf-8")
    raised = False
    try:
        plan(tmp, dpath)
    except ValueError as e:
        raised = "UNRESOLVED" in str(e)
    ok(raised, "an undeclared candidate must refuse the whole plan (R4.9)")

    # --- occurrence-count disagreement must RAISE (R5.2)
    lrn = {"learnable": False, "reason_none": "fixture"}
    base = {"D-2": {"disposition": "MIGRATE", "occurrences_expected": 1, "record_type": "DECISION",
                    "state": "OPEN", "is_fix": False, "learning": lrn},
            "D-1": {"disposition": "ALIAS", "occurrences_expected": 1, "canonical": "ISA-0017",
                    "basis": "row struck through"},
            "H5": {"disposition": "MIGRATE", "occurrences_expected": 1, "record_type": "DEFECT",
                   "state": "DEFERRED", "deferred_until": "2026-11-01", "deferred_reason": "needs capture",
                   "learning": lrn}}
    bad = json.loads(json.dumps(base))
    bad["D-2"]["occurrences_expected"] = 2
    dpath.write_text(json.dumps({"entries": {f"DECISION:{k}": v for k, v in bad.items()}}), encoding="utf-8")
    raised = False
    try:
        plan(tmp, dpath)
    except ValueError as e:
        raised = "OCCURRENCE COUNT DISAGREEMENT" in str(e)
    ok(raised, "a declared occurrence count that disagrees with the document must RAISE (R5.2)")

    # --- stale declaration (declared, but no longer in the source) must RAISE
    stale = json.loads(json.dumps(base))
    stale["D-99"] = {"disposition": "EXCLUDE", "occurrences_expected": 1, "reason": "gone"}
    dpath.write_text(json.dumps({"entries": {f"DECISION:{k}": v for k, v in stale.items()}}), encoding="utf-8")
    raised = False
    try:
        plan(tmp, dpath)
    except ValueError as e:
        raised = "no candidate in the sources" in str(e)
    ok(raised, "a declaration with no candidate must RAISE - a stale declaration is a stale register")

    # --- EXCLUDE without a reason must RAISE
    noreason = json.loads(json.dumps(base))
    noreason["D-2"] = {"disposition": "EXCLUDE", "occurrences_expected": 1}
    dpath.write_text(json.dumps({"entries": {f"DECISION:{k}": v for k, v in noreason.items()}}), encoding="utf-8")
    raised = False
    try:
        plan(tmp, dpath)
    except ValueError as e:
        raised = "without a reason" in str(e)
    ok(raised, "EXCLUDE without a reason must RAISE - silence is not a decision (R4.6)")

    # --- happy path against an isolated store
    import os
    store = tmp / "state"
    store.mkdir()
    schema_src = R.store_dir() / R.SCHEMA_FILE
    if not schema_src.exists():
        schema_src = Path(R.__file__).parent / R.SCHEMA_FILE
    (store / R.SCHEMA_FILE).write_text(schema_src.read_text(encoding="utf-8"), encoding="utf-8")
    old = os.environ.get("ISA_REGISTER_STORE")
    os.environ["ISA_REGISTER_STORE"] = str(store)
    R._schema_cache.clear()
    try:
        dpath.write_text(json.dumps({"entries": {f"DECISION:{k}": v for k, v in base.items()}}),
                         encoding="utf-8")
        p = plan(tmp, dpath)
        ok(len(p["to_migrate"]) == 2 and len(p["aliases"]) == 1,
           f"plan split wrong: {len(p['to_migrate'])}/{len(p['aliases'])}")
        ok("id" not in p["to_migrate"][0],
           "plan() must not allocate an id - it is a read-only operation (ISA-0225)")
        hw_before = json.loads((store / R.HIGHWATER_FILE).read_text(encoding="utf-8"))["highest"] \
            if (store / R.HIGHWATER_FILE).exists() else 0
        plan(tmp, dpath)
        hw_after = json.loads((store / R.HIGHWATER_FILE).read_text(encoding="utf-8"))["highest"] \
            if (store / R.HIGHWATER_FILE).exists() else 0
        ok(hw_before == hw_after,
           f"planning twice must not advance the id high-water mark ({hw_before} -> {hw_after})")
        rec = [r for r in p["to_migrate"] if r["aliases"][0] == "D-2"][0]
        ok(rec["criticality"] == "HIGH" and rec["size_est"] == "S", "fields read off the table")
        ok(rec["provenance"] == "backfilled", "every migrated record is backfilled (R7.5/R6.4)")
        ok("A problem statement" in rec["title"], "title read from the Problem column")
        ok(rec["_migration_basis"]["criticality"] == "Crit column", "criticality basis recorded")
        h5 = [r for r in p["to_migrate"] if r["aliases"][0] == "H5"][0]
        ok(h5["criticality"] == "HIGH", "criticality falls back to the section heading, mechanically")

        man = apply(tmp, dpath, dry_run=False)
        ok(man["migrated"] == 2, f"apply wrote {man['migrated']}")
        ok(R.resolve_alias("DECISION:D-1") == "ISA-0017", "alias rows are written for already-migrated ids")
        again = apply(tmp, dpath, dry_run=False)
        ok(again["migrated"] == 0, "apply is idempotent - a re-run must not duplicate items")

        rec_open = reconcile(tmp, dpath)
        ok(rec_open["reconciled"], f"gate must reconcile after a clean apply: {rec_open}")

        # negative control for the gate: remove an item from the store and it must FAIL
        rows = [r for r in R.read_all() if "D-2" not in r.get("aliases", [])]
        (store / R.ITEMS_FILE).write_text(
            "\n".join(json.dumps(r, ensure_ascii=False, sort_keys=True) for r in rows) + "\n",
            encoding="utf-8")
        broken = reconcile(tmp, dpath)
        ok(not broken["reconciled"] and broken["in_source_not_store"] == ["DECISION:D-2"],
           f"gate negative control failed to fire: {broken}")
    finally:
        if old:
            os.environ["ISA_REGISTER_STORE"] = old
        else:
            os.environ.pop("ISA_REGISTER_STORE", None)
        R._schema_cache.clear()

    # R7.3 / re-runnability: after the live file becomes a render, the gate must still run
    arc = tmp / ARCHIVE_DIR
    arc.mkdir(exist_ok=True)
    original = (tmp / SOURCE_FILES["DECISION"]).read_text(encoding="utf-8")
    (arc / "ISA_Decision_Register_pre_P2_20260812.md").write_text(original, encoding="utf-8")
    (tmp / SOURCE_FILES["DECISION"]).write_text(GENERATED_MARK + "\n# a render\n", encoding="utf-8")
    ok([o.legacy_id for o in extract("DECISION", tmp)] == ["D-2", "D-1", "H5"],
       "extraction must fall back to the archived original once the live path is a render")
    (arc / "ISA_Decision_Register_pre_P2_20260812.md").unlink()
    raised = False
    try:
        extract("DECISION", tmp)
    except FileNotFoundError:
        raised = True
    ok(raised, "a render with no archived original must RAISE, never silently read the render")

    import shutil
    shutil.rmtree(tmp, ignore_errors=True)
    if verbose:
        print(f"isa_register_migrate selftest: {n} assertions, 0 failed")
    return n


def main(argv=None):
    ap = argparse.ArgumentParser(description="P2 migration of the legacy markdown registers")
    ap.add_argument("--root", default=None)
    ap.add_argument("--declarations", default=None)
    ap.add_argument("--extract", action="store_true")
    ap.add_argument("--plan", action="store_true")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--reconcile", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)

    if a.selftest:
        selftest(root=a.root)
        return 0
    if a.extract:
        for src in SOURCE_FILES:
            gs = group_occurrences(extract(src, a.root))
            print(f"\n=== {src}: {len(gs)} distinct ids")
            for k, g in sorted(gs.items(), key=lambda kv: kv[1].first_line):
                print(f"  {k:24} x{len(g.occurrences)}  first@{g.first_line:5}  {g.section[:52]}")
        return 0
    if a.plan:
        p = plan(a.root, a.declarations)
        print(f"groups={p['groups']} declarations={p['declarations']} "
              f"migrate={len(p['to_migrate'])} alias={len(p['aliases'])} exclude={len(p['excluded'])}")
        return 0
    if a.apply:
        m = apply(a.root, a.declarations, dry_run=False)
        print(json.dumps({k: v for k, v in m.items() if k not in ("records", "aliases", "exclusions")}, indent=2))
        return 0
    if a.reconcile:
        r = reconcile(a.root, a.declarations)
        print(json.dumps(r, indent=2))
        return 0 if r["reconciled"] else 1
    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
