"""Render the markdown registers FROM the item store.

Standard: ISA_Engineering_Rules.md.  Spec: ISA_BuildSpec_ItemRegister_4C_09Aug2026.md s6.5, s7.

R7.1  one register. `Dashboard/state/isa_items.jsonl` is canonical; every markdown file
      produced here is a VIEW. A second register is a defect.
R14.3 a generated artefact is never hand-edited. `--check` regenerates and fails on any
      drift, so an edit to a rendered file is caught rather than silently lost.
R4.4  the ranking is a FUNCTION of item fields (isa_register.rank_score) - it is never typed
      here. A hand-maintained rank is a second thing to keep in sync, and the 08-Aug backlog
      proved it drifts within days.

Three views, each written to the path the framework already references so nothing breaks:
  ISA_OPEN_ITEMS_REGISTER.md          - open set, Raj's queue, deferred, closed-this-store
  ISA_Decision_Register.md            - the DECISION class
  ISA_Build_Backlog_Ranked.md         - the computed ranking (replaces the dated 08-Aug file)

CLI:
  python3 isa_register_render.py --write [--dest DIR]
  python3 isa_register_render.py --check [--dest DIR]     # exit 1 on drift
  python3 isa_register_render.py --selftest
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

import isa_register as R

RENDERS = {
    "open_items": "ISA_OPEN_ITEMS_REGISTER.md",
    "decisions": "ISA_Decision_Register.md",
    "backlog": "ISA_Build_Backlog_Ranked.md",
}
ARCHIVE_DIR = "register_archive"
EMDASH = "\u2014"
MID = "\u00b7"
FLAG = "\u2691"
NOT_RECORDED = "Missing(not_recorded_at_the_time)"
GENERATED_MARK = "<!-- GENERATED BY isa_register_render.py - DO NOT EDIT (R14.3) -->"

CRIT_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
LIVE = {"OPEN", "IN_PROGRESS", "BLOCKED_ON_RAJ", "DEFERRED"}


def _dest(dest=None) -> Path:
    return Path(dest).resolve() if dest else Path(__file__).resolve().parent


def _esc(text) -> str:
    """Markdown table cells cannot carry a raw pipe or newline."""
    if text is None:
        return ""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _legacy(item) -> str:
    return ", ".join(a for a in item.get("aliases", []) if ":" not in a) or "—"


EMDASH = "\u2014"
MID = "\u00b7"
FLAG = "\u2691"


def _detail(it) -> list:
    """The item, in full. Spec s10: the narrative is the most valuable content in the
    existing register and is preserved VERBATIM - a table of titles is an index, not a
    register, and reading the pointer instead of the source is a named failure (R2.8)."""
    size = it.get("size_est") or EMDASH
    domain = it.get("domain") or "domain not recorded"
    raised = R.date_raised(it) or "date not recorded"
    out = [f"### `{it['id']}` {EMDASH} {_esc(it['title'])}", "",
           f"`{it['state']}` {MID} **{it['criticality']}** {MID} {it['record_type']}"
           f" {MID} size {size} {MID} {domain} {MID} raised {raised} {MID} legacy {_legacy(it)}"]
    br = it.get("blocks_run") or {}
    if br.get("run_date"):
        out.append(f"{FLAG} **Blocks the {br.get('run_type')} on {br['run_date']}.**")
    if it.get("evidence_basis"):
        line = f"Evidence basis: **{it['evidence_basis']}** (R13.1)."
        if it.get("evidence_note"):
            line += " " + it["evidence_note"]
        if it.get("falsified_by"):
            line += f" Falsified by: {it['falsified_by']}. Revisit by {it.get('revisit_by')}."
        out.append(line)
    if it.get("claim_status"):
        out.append(f"Claim status: **{it['claim_status']}** (R2.2).")
    if it.get("blocked_question"):
        out += ["", "**Question for Raj:** " + it["blocked_question"]]
    if it.get("deferred_until"):
        out += ["", f"**Deferred until {it['deferred_until']}** {EMDASH} {it.get('deferred_reason')}"]
    # The 4Cs, always rendered - including their absence. A blank C and a C nobody recorded
    # are different facts, and hiding the second is how the gap stayed invisible (ISA-0226).
    cs = [("Context", it.get("context")),
          ("Cause (proximate)", it.get("cause_proximate")),
          ("Cause (systemic)", it.get("cause_systemic")),
          ("Consequence", it.get("consequence")),
          ("Corrective action", it.get("corrective_action"))]
    # Always rendered. Skipping the block when every C is empty is precisely how the gap
    # stayed invisible for 73 items - an absent section reads as "nothing to say" (ISA-0226).
    if True:
        out += ["", "**The 4Cs**", ""]
        for label, val in cs:
            if not val:
                out.append(f"- **{label}.** _not recorded_")
            elif val == NOT_RECORDED:
                out.append(f"- **{label}.** _{NOT_RECORDED}_ \u2014 absent from the source and "
                           f"deliberately not invented (R7.5)")
            else:
                out.append(f"- **{label}.** {val}")
        q = it.get("consequence_quantified")
        if q:
            out.append(f"- **Quantified.** {q.get('value')} {q.get('unit','')} "
                       f"({q.get('metric','')}) \u2014 basis: {q.get('basis','')}")
        else:
            out.append("- **Quantified.** _not recorded_ \u2014 R13.3: a consequence without a "
                       "number cannot be ranked against anything")
    if it.get("disagreement"):
        out += ["", "**Disagreement (published, never blended " + EMDASH + " R6.2).** "
                + it["disagreement"]]
    nar = (it.get("narrative") or "").strip()
    if nar:
        quoted = "\n".join(("> " + l) if l.strip() else ">" for l in nar.splitlines())
        out += ["", "<details><summary>Source text, verbatim</summary>", "", quoted, "", "</details>"]
    st = it.get("studies") or []
    if st:
        out += ["", f"**Studies undertaken ({len(st)}):**"]
        for d in st:
            flag = "" if d.get("on_disk") else "  \u26a0 **NOT ON DISK**"
            out.append(f"- `{d['doc']}`{flag} {MID} {d.get('basis') or ''}")
            if d.get("finding"):
                out.append(f"  - matched: *{d['finding']}*")
    else:
        out += ["", "**Studies undertaken:** none linked. Under R13.2 analysis precedes design, "
                    "so this is either pre-analysis work or an item whose evidence is no longer "
                    "reachable from it."]
    if it.get("source_doc"):
        prov = it.get("provenance")
        out += ["", f"*Source: {it['source_doc']} {MID} provenance `{prov}`*"]
    out.append("")
    return out


def _header(title: str, subtitle: str, as_of: str) -> list:
    return [
        GENERATED_MARK,
        f"# {title}",
        "",
        f"**Generated {as_of} by `isa_register_render.py` from `Dashboard/state/isa_items.jsonl`.**",
        "**This file is a VIEW. Do not edit it — edit the store via `isa_register.py` (R7.1, R14.3).**",
        f"An edit here is detected by `isa_register_render.py --check` and lost on the next render.",
        "",
        subtitle,
        "",
    ]


def _counts_block(items) -> list:
    live = [i for i in items if i["state"] in LIVE]
    out = ["## Counts", "",
           "| | CRITICAL | HIGH | MEDIUM | LOW | total |", "|---|---|---|---|---|---|"]
    for state in ["OPEN", "IN_PROGRESS", "BLOCKED_ON_RAJ", "DEFERRED"]:
        row = [i for i in live if i["state"] == state]
        cells = [str(sum(1 for i in row if i["criticality"] == c)) for c in CRIT_ORDER]
        out.append(f"| **{state}** | " + " | ".join(cells) + f" | **{len(row)}** |")
    cells = [str(sum(1 for i in live if i["criticality"] == c)) for c in CRIT_ORDER]
    out.append("| **all live** | " + " | ".join(cells) + f" | **{len(live)}** |")
    closed = [i for i in items if i["state"] in R.CLOSED_STATES]
    fix = sum(1 for i in live if i.get("is_fix"))
    out += ["",
            f"Closed in this store: **{len(closed)}**. "
            f"Live items that are FIXES rather than enhancements: **{fix} of {len(live)}** "
            f"(K1's numerator; see `ISA_Engineering_Rules.md` §10).",
            "",
            "⚑ **Counts before Sep-2026 are `indicative`, not measured** — migrated records carry "
            "`provenance: backfilled` and their 4Cs were never invented retrospectively (R7.5).",
            ""]
    return out


def _studies_cell(it) -> str:
    """Studies undertaken for this item (ISA-0212, Raj 12-Aug-2026).

    Shows the count, marks a PRIMARY study in bold, and marks any named study that is not on
    disk. `--` means no study is linked - which is a STATEMENT, not a blank: under R13.2
    analysis precedes design, so an item with no study is either pre-analysis or has lost the
    link to its own evidence. Both are worth seeing."""
    st = it.get("studies") or []
    if not st:
        return "—"
    bits = []
    for d in st:
        name = d["doc"].replace(".md", "")
        if not d.get("on_disk"):
            bits.append(f"{name} ⚠NOT ON DISK")
        elif "PRIMARY" in (d.get("basis") or ""):
            bits.append(f"**{name}**")
        else:
            bits.append(name)
    return f"{len(st)}: " + "; ".join(bits)


def _item_table(rows, today) -> list:
    out = ["| Rank | ID | Legacy | Criticality | Size | Domain | Studies | Title |",
           "|---|---|---|---|---|---|---|---|"]
    for i, it in enumerate(rows, 1):
        out.append(
            f"| {i} | `{it['id']}` | {_esc(_legacy(it))} | {it['criticality']} | "
            f"{it.get('size_est') or '—'} | {it.get('domain') or '—'} | "
            f"{_esc(_studies_cell(it))} | {_esc(it['title'])} |")
    return out


def render_open_items(items, as_of, today) -> str:
    ranked = R.ranked(today=today)
    queue = sorted(R.raj_queue(), key=lambda i: (CRIT_ORDER.index(i["criticality"]), i["id"]))
    deferred = sorted([i for i in items if i["state"] == "DEFERRED"], key=lambda i: i["id"])
    closed = sorted([i for i in items if i["state"] in R.CLOSED_STATES], key=lambda i: i["id"])

    L = _header(
        "ISA Framework — Open Items Register",
        "Everything the framework is carrying, with severity, state and the rule it was built "
        "against. Ranking is **computed** from item fields (BuildSpec §7.1) and is never typed.",
        as_of)
    L += _counts_block(items)

    L += ["---", "", "## Build queue — computed, in order", "",
          "Ordered by: blocks the next scheduled run · irreversibility · capital impact · "
          "criticality · size as a tiebreak only. `BLOCKED_ON_RAJ` items are a separate list "
          "below — mixing a decision you owe with a build I owe hides both.", ""]
    L += _item_table(ranked, today)

    blockers = [i for i in ranked if (i.get("blocks_run") or {}).get("run_date")]
    if blockers:
        L += ["", "### Items with a hard run deadline", "",
              "| ID | Run | Date | Title |", "|---|---|---|---|"]
        for it in blockers:
            br = it["blocks_run"]
            L.append(f"| `{it['id']}` | {br.get('run_type')} | {br.get('run_date')} | {_esc(it['title'])} |")

    L += ["", "---", "", f"## Raj's queue — {len(queue)} decisions waiting", "",
          "KR8 fires at three items older than one run cycle.", ""]
    for it in queue:
        L += _detail(it)

    if deferred:
        L += ["---", "", f"## Deferred by design — {len(deferred)}", "",
              "Excluded from the ranked queue until their date, so they do not pollute ageing (K13).", "",
              "| ID | Legacy | Until | Title | Reason |", "|---|---|---|---|---|"]
        for it in deferred:
            L.append(f"| `{it['id']}` | {_esc(_legacy(it))} | {it.get('deferred_until')} | "
                     f"{_esc(it['title'])} | {_esc(it.get('deferred_reason'))} |")
        L.append("")

    L += ["---", "", f"## Closed in this store — {len(closed)}", "",
          "`CLOSED_FIXED` requires a green liveness reference; `isa_register.close()` refuses "
          "without one, because a corrective action with no check that catches recurrence is a "
          "narrative claim (R7.3, R5.4).", "",
          "| ID | Legacy | State | Title | Liveness reference |", "|---|---|---|---|---|"]
    for it in closed:
        ver = it.get("verification") or {}
        L.append(f"| `{it['id']}` | {_esc(_legacy(it))} | {it['state']} | {_esc(it['title'])} | "
                 f"{_esc(ver.get('liveness_ref') or '—')} |")

    live_detail = sorted([i for i in items if i["state"] in LIVE and i["state"] != "BLOCKED_ON_RAJ"],
                         key=lambda i: (-R.rank_score(i, today), i["id"]))
    L += ["", "---", "", f"## Every live item, in full {EMDASH} {len(live_detail)}", "",
          "In build-queue order. `BLOCKED_ON_RAJ` items are above, with their questions.", ""]
    for it in live_detail:
        L += _detail(it)

    try:
        import isa_register_migrate as _M
        st = _M.fourc_status(items)
        nlive = st.pop("_live")
        L += ["", "---", "", "## The 4Cs \u2014 completeness (R7.2)", "",
              "**stated** = recorded, and where it came from travels with it. "
              "**declared absent** = the source did not record it and it was deliberately not "
              "invented (R7.5). **silently absent** must be zero \u2014 a field that is blank for "
              "no stated reason is the null-vs-missing class in the register itself.", "",
              f"| C | stated | declared absent | silently absent | of {nlive} live |",
              "|---|---|---|---|---|"]
        for f, v in st.items():
            L.append(f"| `{f}` | {v['stated']} | {v['declared_absent']} | "
                     f"{v['silently_absent']} | {nlive} |")
        L += ["", "⚑ `cause_systemic` is declared-absent on every migrated item **by design**: it "
                  "is not written anywhere in the legacy registers, and manufacturing it is what "
                  "R7.5 refuses. It is filled when an item is worked, not before.", ""]
    except Exception as _e:                                       # noqa: BLE001
        L += ["", f"*(4C completeness unavailable: {_e})*", ""]

    with_study = [i for i in items if i.get("studies")]
    absent = [(i["id"], d["doc"]) for i in items for d in (i.get("studies") or [])
              if not d.get("on_disk")]
    orph = R.orphan_studies()
    L += ["", "---", "", "## Studies — coverage", "",
          f"**{len(with_study)} of {len(items)} items** link to at least one research artefact. "
          f"Links are DECLARED, never inferred: a study is either named in the item's own text "
          f"or names the item's legacy id, and the matched line travels with it (R2.7, R4.2).", ""]
    if absent:
        L += [f"⚑ **{len(absent)} named studies are NOT on disk** — reported, never dropped (R4.9):", ""]
        L += [f"- `{doc}` (named by {iid})" for iid, doc in sorted(set(absent))]
        L += [""]
    L += [f"⚑ **{len(orph)} research artefacts on disk are referenced by NO item.** Analysis that "
          f"no item points at is analysis nobody will find again — this is the other half of the "
          f"same question and it is the honest measure of how much evidence has come loose from "
          f"the work it justifies:", ""]
    L += [f"- `{o}`" for o in orph] + [""]

    L += ["", "---", "", "## What is NOT in this file", "",
          f"The pre-P2 narrative — every session record from 02-Aug-2026 to 09-Aug-2026, ~1,500 "
          f"lines — is preserved verbatim at `{ARCHIVE_DIR}/`. It is **not** lost and it is "
          "**not** migrated: the full closed-history migration is **P5**, and inventing 4Cs for "
          "historical items is refused (R7.5). Nothing was deleted (R6.5).", "",
          "Legacy ids resolve through `Dashboard/state/isa_id_map.json`, qualified by source — "
          "the sources carried four unrelated `D-` schemes and two different `D1`s in one file, "
          "so a legacy id is never used as a store id (R7.6).", ""]
    return "\n".join(L) + "\n"


def render_decisions(items, as_of, today) -> str:
    dec = [i for i in items if i["record_type"] == "DECISION"]
    live = sorted([i for i in dec if i["state"] in LIVE],
                  key=lambda i: (-R.rank_score(i, today), i["id"]))
    closed = sorted([i for i in dec if i["state"] in R.CLOSED_STATES], key=lambda i: i["id"])
    L = _header("ISA Decision Register",
                "The `DECISION` class of the item store. **This is no longer a separate register** "
                "— it is a filtered view, which is what P8/R7.1 requires.", as_of)
    L += [f"**{len(live)} live · {len(closed)} closed.**", "",
          "## Live decisions", ""] + _item_table(live, today)
    L += ["", "## Closed decisions", "",
          "| ID | Legacy | State | Title | Basis for closure |", "|---|---|---|---|---|"]
    for it in closed:
        ver = it.get("verification") or {}
        basis = ver.get("liveness_ref") or it.get("wontfix_accepted_by") or it.get("corrective_action") or "—"
        L.append(f"| `{it['id']}` | {_esc(_legacy(it))} | {it['state']} | {_esc(it['title'])} | {_esc(basis)} |")
    L += ["", "---", "",
          "**Standing rules** are not restated here. They live once, in "
          "`ISA_Engineering_Rules.md` (O-10, R4.4): D-20 → §2 · D-26 → R4.6 · D-27 → R2.11.", ""]
    return "\n".join(L) + "\n"


def render_backlog(items, as_of, today) -> str:
    ranked = R.ranked(today=today)
    L = _header("ISA Framework — Ranked Build Backlog",
                "**Computed on read, never typed.** The 08-Aug-2026 hand-compiled backlog is "
                "retired: within one day it was stale, and it sent a session to an already-closed "
                "item (ISA-0024). A hand-maintained rank is a second thing to keep in sync.", as_of)
    for code, label in [(c, l) for _f, c, l in R.PRIORITY_TIERS]:
        name = f"{code} \u2014 {label}"
        rows = [i for i in ranked if R.tier(i, today)[0] == code]
        L += [f"## {name} — {len(rows)}", ""]
        L += _item_table(rows, today) if rows else ["*(none)*"]
        L += [""]
    L += ["---", "",
          "Tiers are cut from `isa_register.rank_score()`; the boundaries are the weights in that "
          "function (run-blocker 1000 · irreversible 500 · capital impact 200 · criticality). "
          "Change the weights in one place and every view moves together (R4.4).", ""]
    return "\n".join(L) + "\n"


def build_all(as_of=None, today=None) -> dict:
    items = R.read_all()
    as_of = as_of or R._today()
    today = today or date.today()
    return {"open_items": render_open_items(items, as_of, today),
            "decisions": render_decisions(items, as_of, today),
            "backlog": render_backlog(items, as_of, today)}


def archive_originals(dest=None, as_of=None) -> list:
    """Move the hand-written originals aside BEFORE the first render overwrites them.

    Never deleted, never overwritten: if an archive copy already exists it is left alone,
    because a second run must not replace the original with a generated file (R6.5).
    """
    d = _dest(dest)
    arc = d / ARCHIVE_DIR
    arc.mkdir(exist_ok=True)
    as_of = (as_of or R._today()).replace("-", "")
    moved = []
    for key, name in RENDERS.items():
        src = d / name
        if not src.exists():
            continue
        if GENERATED_MARK in src.read_text(encoding="utf-8")[:400]:
            continue  # already a render; nothing hand-written to preserve
        target = arc / f"{Path(name).stem}_pre_P2_{as_of}.md"
        if not target.exists():
            target.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            moved.append(str(target.relative_to(d)))
    legacy_backlog = d / "ISA_Build_Backlog_Ranked_08Aug2026.md"
    if legacy_backlog.exists():
        t = arc / f"ISA_Build_Backlog_Ranked_pre_P2_{as_of}.md"
        if not t.exists():
            t.write_text(legacy_backlog.read_text(encoding="utf-8"), encoding="utf-8")
            moved.append(str(t.relative_to(d)))
    return moved


def write(dest=None, as_of=None, today=None) -> dict:
    d = _dest(dest)
    archived = archive_originals(dest, as_of)
    out = build_all(as_of, today)
    written = {}
    for key, text in out.items():
        (d / RENDERS[key]).write_text(text, encoding="utf-8")
        written[RENDERS[key]] = len(text)
    return {"archived": archived, "written": written}


def check(dest=None, as_of=None, today=None) -> dict:
    """R14.3 / R15.4: a rendered file that differs from what the store produces is DRIFT.

    Either someone hand-edited a view - in which case the edit is about to be lost and the
    store never learned of it - or the store moved and the view was not refreshed. Both are
    the same defect: a document that says one thing and is another.
    """
    d = _dest(dest)
    out = build_all(as_of, today)
    drift = []
    for key, text in out.items():
        p = d / RENDERS[key]
        if not p.exists():
            drift.append(f"{RENDERS[key]}: absent - never rendered")
        elif p.read_text(encoding="utf-8") != text:
            drift.append(f"{RENDERS[key]}: differs from the store's render")
    return {"ok": not drift, "drift": drift}


def selftest(verbose=True) -> int:
    import json, os, shutil, tempfile
    n = 0

    def ok(cond, msg):
        nonlocal n
        n += 1
        if not cond:
            raise AssertionError(msg)

    tmp = Path(tempfile.mkdtemp(prefix="isa_render_"))
    store = tmp / "state"
    store.mkdir()
    schema = R.store_dir() / R.SCHEMA_FILE
    if not schema.exists():
        schema = Path(R.__file__).parent / R.SCHEMA_FILE
    (store / R.SCHEMA_FILE).write_text(schema.read_text(encoding="utf-8"), encoding="utf-8")
    old = os.environ.get("ISA_REGISTER_STORE")
    os.environ["ISA_REGISTER_STORE"] = str(store)
    R._schema_cache.clear()
    try:
        lrn = {"learnable": False, "reason_none": "fixture"}
        CS = {"context": "render selftest fixture, 13-Aug-2026",
              "cause_proximate": "fixture proximate cause",
              "cause_systemic": "fixture systemic cause",
              "consequence": "fixture consequence",
              "corrective_action": "fixture corrective action"}   # ISA-0337: the gate binds here too
        R.intake("Blocks the September pre-run", record_type="DEFECT", criticality="MEDIUM",
                 intake_trigger="build_discovery", detected_by="CLAUDE_BUILD", learning=lrn, **CS,
                 blocks_run={"run_type": "monthly_prerun", "run_date": "2026-09-05"}, size_est="S")
        R.intake("A decision Raj owes", record_type="DECISION", criticality="HIGH", is_fix=False,
                 intake_trigger="raj_request", detected_by="RAJ", learning=lrn, **CS,
                 state="BLOCKED_ON_RAJ", blocked_question="Nine per cent or twelve?")
        R.intake("Parked until November", record_type="RESEARCH", criticality="HIGH",
                 intake_trigger="retrospective", detected_by="CLAUDE_REVIEW", learning=lrn, **CS,
                 state="DEFERRED", deferred_until="2026-11-01", deferred_reason="needs three months of capture")
        R.intake("A pipe | in the title and a CRITICAL rank", record_type="DEFECT",
                 criticality="CRITICAL", intake_trigger="build_discovery",
                 detected_by="CLAUDE_BUILD", learning=lrn, **CS, size_est="XS")

        today = date(2026, 8, 12)
        out = build_all(as_of="2026-08-12", today=today)
        oi = out["open_items"]
        ok(GENERATED_MARK in oi, "every render carries the do-not-edit marker (R14.3)")
        ok(re.search(r"raised \d{2}-[A-Z][a-z]{2}-\d{2}", oi),
           "ISA-0338: every rendered item states the date it was raised, dd-mmm-yy")
        ok("Nine per cent or twelve?" in oi, "the blocked question is rendered verbatim")
        ok("Every live item, in full" in oi, "live items are rendered in full, not only as a table")
        ok("| Studies |" in oi, "every item table carries a Studies column (ISA-0212)")
        ok("The 4Cs \u2014 completeness" in oi, "the view publishes 4C completeness (ISA-0226)")
        ok("**The 4Cs**" in oi, "every live item renders its 4Cs, including their absence")
        ok("Studies \u2014 coverage" in oi, "the view states study coverage and the orphan list")
        ok(_studies_cell({}) == "\u2014", "no study renders as a stated dash, never an empty cell")
        ok("**A_Study_x**" in _studies_cell(
            {"studies": [{"doc": "A_Study_x.md", "on_disk": True, "basis": "PRIMARY subject"}]}),
           "a PRIMARY study is marked in bold")
        ok("NOT ON DISK" in _studies_cell(
            {"studies": [{"doc": "Gone_Study.md", "on_disk": False, "basis": "named in text"}]}),
           "a named study absent from disk is flagged, never silently dropped (R4.9)")
        ok("A decision Raj owes" not in oi.split("Raj's queue")[0],
           "a BLOCKED_ON_RAJ item must not appear in the build queue (BuildSpec s7.3)")
        ok("Parked until November" in oi and "2026-11-01" in oi, "deferred items are rendered with their date")
        ok(r"pipe \| in the title" in oi, "a pipe in a title is escaped, never breaking the table")
        first_row = [l for l in oi.splitlines() if l.startswith("| 1 |")][0]
        ok("Blocks the September pre-run" in first_row,
           f"the run-blocker must rank first, got: {first_row[:90]}")

        ok("Nine per cent or twelve?" in out["decisions"] or "A decision Raj owes" in out["decisions"],
           "the decision view carries DECISION-class items")
        ok("P0 — blocks the next scheduled run — 1" in out["backlog"],
           "the backlog tiers are cut from rank_score, not typed")

        # --check: absent -> drift; written -> ok; hand-edited -> drift again
        d2 = tmp / "dest"
        d2.mkdir()
        ok(not check(d2, "2026-08-12", today)["ok"], "an unrendered view is drift")
        res = write(d2, "2026-08-12", today)
        ok(len(res["written"]) == 3, "three views are written")
        ok(check(d2, "2026-08-12", today)["ok"], "a freshly written render must check clean")
        p = d2 / RENDERS["open_items"]
        p.write_text(p.read_text(encoding="utf-8") + "\nhand-edited line\n", encoding="utf-8")
        chk = check(d2, "2026-08-12", today)
        ok(not chk["ok"] and "differs" in chk["drift"][0],
           "a hand-edited view must FAIL --check (R14.3 negative control)")

        # archiving preserves the original and never overwrites it on a second run
        d3 = tmp / "dest3"
        d3.mkdir()
        (d3 / RENDERS["open_items"]).write_text("ORIGINAL HAND-WRITTEN CONTENT\n", encoding="utf-8")
        write(d3, "2026-08-12", today)
        arc = d3 / ARCHIVE_DIR / "ISA_OPEN_ITEMS_REGISTER_pre_P2_20260812.md"
        ok(arc.exists() and "ORIGINAL HAND-WRITTEN" in arc.read_text(encoding="utf-8"),
           "the hand-written original is archived verbatim before the first render")
        write(d3, "2026-08-12", today)
        ok("ORIGINAL HAND-WRITTEN" in arc.read_text(encoding="utf-8"),
           "a second render must NOT overwrite the archive with the generated file (R6.5)")
    finally:
        if old:
            os.environ["ISA_REGISTER_STORE"] = old
        else:
            os.environ.pop("ISA_REGISTER_STORE", None)
        R._schema_cache.clear()
        shutil.rmtree(tmp, ignore_errors=True)
    if verbose:
        print(f"isa_register_render selftest: {n} assertions, 0 failed")
    return n


def main(argv=None):
    ap = argparse.ArgumentParser(description="Render the markdown registers from the item store")
    ap.add_argument("--dest", default=None)
    ap.add_argument("--as-of", default=None)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)
    if a.selftest:
        selftest()
        return 0
    if a.write:
        import json
        print(json.dumps(write(a.dest, a.as_of), indent=2))
        return 0
    if a.check:
        r = check(a.dest, a.as_of)
        print("render check: OK" if r["ok"] else "render DRIFT:\n  - " + "\n  - ".join(r["drift"]))
        return 0 if r["ok"] else 1
    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
